In [338]:
# ========================================
# IMPORT LIBRARIES
# ========================================
import pandas as pd
import numpy as np
import json
import dill 
from IPython.display import display
from datetime import datetime

In [ ]:
# ========================================
# LOAD/SAVE SESSIONS
# ========================================
#filename = 'notebook_env_analysis.db'
#dill.dump_session(filename)

# and to load the session again:
#dill.load_session(filename)

In [3]:
# ========================================
# READ/EXTRACT RELEVANT DATA
# ========================================
with open("data/Kickstarter_2018-10-18T03_20_48_880Z/Kickstarter_2018-10-18T03_20_48_880Z.json",
          encoding="utf8") as json_file:
    json_obj = [json.loads(line) for line in json_file]

In [4]:
# ---- QUICK EXPLORATION ----

In [4]:
type(json_obj)

list

In [5]:
len(json_obj)

205696

In [6]:
type(json_obj[0])

dict

In [7]:
len(json_obj[0])

4

In [8]:
json_obj[len(json_obj)-1] # look at final entry

{'table_id': 'Kickstarter',
 'robot_id': 'Kickstarter',
 'run_id': 'Kickstarter_2018-10-18T03_20_48_880Z',
 'data': {'id': 1991284368,
  'photo': {'key': 'assets/011/796/998/9d7e9715ca5b8227f29de01f3c4abc8f_original.png',
   'full': 'https://ksr-ugc.imgix.net/assets/011/796/998/9d7e9715ca5b8227f29de01f3c4abc8f_original.png?ixlib=rb-1.1.0&crop=faces&w=560&h=315&fit=crop&v=1463696010&auto=format&frame=1&q=92&s=02368a096ce01fc6cae29ab85df52d53',
   'ed': 'https://ksr-ugc.imgix.net/assets/011/796/998/9d7e9715ca5b8227f29de01f3c4abc8f_original.png?ixlib=rb-1.1.0&crop=faces&w=352&h=198&fit=crop&v=1463696010&auto=format&frame=1&q=92&s=7c87714e96670269be821591da0ddbb1',
   'med': 'https://ksr-ugc.imgix.net/assets/011/796/998/9d7e9715ca5b8227f29de01f3c4abc8f_original.png?ixlib=rb-1.1.0&crop=faces&w=272&h=153&fit=crop&v=1463696010&auto=format&frame=1&q=92&s=7ce6128059b609c7603ab19d113e7c55',
   'little': 'https://ksr-ugc.imgix.net/assets/011/796/998/9d7e9715ca5b8227f29de01f3c4abc8f_original.png?ixlib=rb-1.1.0&crop=faces&w=208&h=117&fit=crop&v=1463696010&auto=format&frame=1&q=92&s=04ea8b7b8a8eb7da2cda7e77c44eab8e',
   'small': 'https://ksr-ugc.imgix.net/assets/011/796/998/9d7e9715ca5b8227f29de01f3c4abc8f_original.png?ixlib=rb-1.1.0&crop=faces&w=160&h=90&fit=crop&v=1463696010&auto=format&frame=1&q=92&s=cb7054d89e3115543343be1d167ccc80',
   'thumb': 'https://ksr-ugc.imgix.net/assets/011/796/998/9d7e9715ca5b8227f29de01f3c4abc8f_original.png?ixlib=rb-1.1.0&crop=faces&w=48&h=27&fit=crop&v=1463696010&auto=format&frame=1&q=92&s=b56e49b8d16b5b9d63de0a0fc7c78ee0',
   '1024x576': 'https://ksr-ugc.imgix.net/assets/011/796/998/9d7e9715ca5b8227f29de01f3c4abc8f_original.png?ixlib=rb-1.1.0&crop=faces&w=1024&h=576&fit=crop&v=1463696010&auto=format&frame=1&q=92&s=766fc63209f2030f8adb9ef1010dbbd8',
   '1536x864': 'https://ksr-ugc.imgix.net/assets/011/796/998/9d7e9715ca5b8227f29de01f3c4abc8f_original.png?ixlib=rb-1.1.0&crop=faces&w=1552&h=873&fit=crop&v=1463696010&auto=format&frame=1&q=92&s=bc19bfa1b4335b14d9119ef9ba5f0591'},
  'name': 'Get Hula Cowgirl Shaved Ice Over the Last Bump!',
  'blurb': 'We are opening what we hope will be a wonderful shaved ice experience for the residents of and visitors to Georgetown, Texas!',
  'goal': 3000,
  'pledged': 35,
  'state': 'failed',
  'slug': 'get-hula-cowgirl-shaved-ice-over-the-last-bump',
  'disable_communication': False,
  'country': 'US',
  'currency': 'USD',
  'currency_symbol': '$',
  'currency_trailing_code': True,
  'deadline': 1408057020,
  'state_changed_at': 1408057020,
  'created_at': 1405914894,
  'launched_at': 1406739106,
  'staff_pick': False,
  'is_starrable': False,
  'backers_count': 3,
  'static_usd_rate': 1,
  'usd_pledged': '35.0',
  'converted_pledged_amount': 35,
  'fx_rate': 1,
  'current_currency': 'USD',
  'usd_type': 'international',
  'creator': {'id': 923311576,
   'name': 'Virginia Keeley',
   'is_registered': True,
   'chosen_currency': None,
   'avatar': {'thumb': 'https://ksr-ugc.imgix.net/assets/009/082/074/38f1f75e252ef1a1618f5a8f1b553816_original.jpg?ixlib=rb-1.1.0&w=40&h=40&fit=crop&v=1461556778&auto=format&frame=1&q=92&s=3e2a419f117c09a1616c245bba3391cc',
    'small': 'https://ksr-ugc.imgix.net/assets/009/082/074/38f1f75e252ef1a1618f5a8f1b553816_original.jpg?ixlib=rb-1.1.0&w=160&h=160&fit=crop&v=1461556778&auto=format&frame=1&q=92&s=178011af1e24a9fa714fea5902fcd0cd',
    'medium': 'https://ksr-ugc.imgix.net/assets/009/082/074/38f1f75e252ef1a1618f5a8f1b553816_original.jpg?ixlib=rb-1.1.0&w=160&h=160&fit=crop&v=1461556778&auto=format&frame=1&q=92&s=178011af1e24a9fa714fea5902fcd0cd'},
   'urls': {'web': {'user': 'https://www.kickstarter.com/profile/923311576'},
    'api': {'user': 'https://api.kickstarter.com/v1/users/923311576?signature=1539925746.73341825197dafd9c6241dd19a4bcc1b9b77f449'}}},
  'location': {'id': 2409678,
   'name': 'Georgetown',
   'slug': 'georgetown-tx',
   'short_name': 'Georgetown, TX',
   'displayable_name': 'Georgetown, TX',
   'localized_name': 'Georgetown',
   'country': 'US',
   'state': 'TX',
   'type': 'Town',
   'is_root': False,
   'urls': {'web': {'discover': 'https://www.kickstarter.com/discover/places/georgetown-tx',
     'location': 'https://www.kickstarter.com/locations/georgetown-tx'},
    'api': {'nearby_projects': 'https://api.kickstarter.com/v1/discover?signature=1539904425.aa4d5a1dc3262bf79c2d1691682064f3a8be1686&woe_id=2409678'}}},
  'category': {'id': 312,
   'name': 'Restaurants',
   'slug': 'food/restaurants',
   'position': 9,
   'parent_id': 10,
   'color': 16725570,
   'urls': {'web': {'discover': 'http://www.kickstarter.com/discover/categories/food/restaurants'}}},
  'profile': {'id': 1208668,
   'project_id': 1208668,
   'state': 'inactive',
   'state_changed_at': 1425915867,
   'name': None,
   'blurb': None,
   'background_color': None,
   'text_color': None,
   'link_background_color': None,
   'link_text_color': None,
   'link_text': None,
   'link_url': None,
   'show_feature_image': False,
   'background_image_opacity': 0.8,
   'should_show_feature_image_section': True,
   'feature_image_attributes': {'image_urls': {'default': 'https://ksr-ugc.imgix.net/assets/011/796/998/9d7e9715ca5b8227f29de01f3c4abc8f_original.png?ixlib=rb-1.1.0&crop=faces&w=1552&h=873&fit=crop&v=1463696010&auto=format&frame=1&q=92&s=bc19bfa1b4335b14d9119ef9ba5f0591',
     'baseball_card': 'https://ksr-ugc.imgix.net/assets/011/796/998/9d7e9715ca5b8227f29de01f3c4abc8f_original.png?ixlib=rb-1.1.0&crop=faces&w=560&h=315&fit=crop&v=1463696010&auto=format&frame=1&q=92&s=02368a096ce01fc6cae29ab85df52d53'}}},
  'spotlight': False,
  'urls': {'web': {'project': 'https://www.kickstarter.com/projects/923311576/get-hula-cowgirl-shaved-ice-over-the-last-bump?ref=category_newest',
    'rewards': 'https://www.kickstarter.com/projects/923311576/get-hula-cowgirl-shaved-ice-over-the-last-bump/rewards'}},
  'source_url': 'https://www.kickstarter.com/discover/categories/food/restaurants'}}

In [9]:
json_obj[0].keys()

dict_keys(['table_id', 'robot_id', 'run_id', 'data'])

In [10]:
# The useful keys are 'data'

In [11]:
# Extract relevant data
# pre-allocate
json_obj2 = []
# append 'data' dictionary only
for x in range(0, len(json_obj)):
    json_obj2.append(json_obj[x]["data"])

In [12]:
len(json_obj2) - len(json_obj) # Check that all rows extracted

0

In [13]:
json_obj2[0]

{'id': 895922629,
 'photo': {'key': 'assets/011/911/160/2ff8292ff8ad7486f38ea865a9c030bb_original.jpg',
  'full': 'https://ksr-ugc.imgix.net/assets/011/911/160/2ff8292ff8ad7486f38ea865a9c030bb_original.jpg?ixlib=rb-1.1.0&crop=faces&w=560&h=315&fit=crop&v=1463713991&auto=format&frame=1&q=92&s=846b5db7dd4a36491881770969721fab',
  'ed': 'https://ksr-ugc.imgix.net/assets/011/911/160/2ff8292ff8ad7486f38ea865a9c030bb_original.jpg?ixlib=rb-1.1.0&crop=faces&w=352&h=198&fit=crop&v=1463713991&auto=format&frame=1&q=92&s=c2d76a75d1cd815488d3d3b651b49222',
  'med': 'https://ksr-ugc.imgix.net/assets/011/911/160/2ff8292ff8ad7486f38ea865a9c030bb_original.jpg?ixlib=rb-1.1.0&crop=faces&w=272&h=153&fit=crop&v=1463713991&auto=format&frame=1&q=92&s=f938afb8f27ea25f81b3f57bc8349d88',
  'little': 'https://ksr-ugc.imgix.net/assets/011/911/160/2ff8292ff8ad7486f38ea865a9c030bb_original.jpg?ixlib=rb-1.1.0&crop=faces&w=208&h=117&fit=crop&v=1463713991&auto=format&frame=1&q=92&s=69632b0cf7a30977d7eb58a05f3bd315',
  'small': 'https://ksr-ugc.imgix.net/assets/011/911/160/2ff8292ff8ad7486f38ea865a9c030bb_original.jpg?ixlib=rb-1.1.0&crop=faces&w=160&h=90&fit=crop&v=1463713991&auto=format&frame=1&q=92&s=348d4ae4d6510c9b470edb3e3e820f73',
  'thumb': 'https://ksr-ugc.imgix.net/assets/011/911/160/2ff8292ff8ad7486f38ea865a9c030bb_original.jpg?ixlib=rb-1.1.0&crop=faces&w=48&h=27&fit=crop&v=1463713991&auto=format&frame=1&q=92&s=e9616d563b12303f8fea361ef31478b2',
  '1024x576': 'https://ksr-ugc.imgix.net/assets/011/911/160/2ff8292ff8ad7486f38ea865a9c030bb_original.jpg?ixlib=rb-1.1.0&crop=faces&w=1024&h=576&fit=crop&v=1463713991&auto=format&frame=1&q=92&s=fb504f53f9713cded89f1264d5f1c6ef',
  '1536x864': 'https://ksr-ugc.imgix.net/assets/011/911/160/2ff8292ff8ad7486f38ea865a9c030bb_original.jpg?ixlib=rb-1.1.0&crop=faces&w=1552&h=873&fit=crop&v=1463713991&auto=format&frame=1&q=92&s=f57666c5f7328d47e63f8b389a84bfef'},
 'name': 'Jozii-College Jobs Made Easy',
 'blurb': 'Jozii is the premier service for full-time university students to find paid part-time work and internships.',
 'goal': 3500,
 'pledged': 50,
 'state': 'failed',
 'slug': 'jozii-college-jobs-made-easy',
 'disable_communication': False,
 'country': 'US',
 'currency': 'USD',
 'currency_symbol': '$',
 'currency_trailing_code': True,
 'deadline': 1417150740,
 'state_changed_at': 1417150742,
 'created_at': 1413476386,
 'launched_at': 1414525374,
 'staff_pick': False,
 'is_starrable': False,
 'backers_count': 1,
 'static_usd_rate': 1,
 'usd_pledged': '50.0',
 'converted_pledged_amount': 50,
 'fx_rate': 1,
 'current_currency': 'USD',
 'usd_type': 'international',
 'creator': {'id': 69089661,
  'name': 'AJ Smith and Brandon Maier (deleted)',
  'slug': 'joziijobs',
  'is_registered': True,
  'chosen_currency': None,
  'avatar': {'thumb': 'https://ksr-ugc.imgix.net/missing_user_avatar.png?ixlib=rb-1.1.0&w=40&h=40&fit=crop&v=&auto=format&frame=1&q=92&s=c8baefb239621e7b5b26957577e078db',
   'small': 'https://ksr-ugc.imgix.net/missing_user_avatar.png?ixlib=rb-1.1.0&w=160&h=160&fit=crop&v=&auto=format&frame=1&q=92&s=fea4448b425bb704dead957d7448b9cc',
   'medium': 'https://ksr-ugc.imgix.net/missing_user_avatar.png?ixlib=rb-1.1.0&w=160&h=160&fit=crop&v=&auto=format&frame=1&q=92&s=fea4448b425bb704dead957d7448b9cc'},
  'urls': {'web': {'user': 'https://www.kickstarter.com/profile/joziijobs'},
   'api': {'user': 'https://api.kickstarter.com/v1/users/69089661?signature=1539920420.2da0e34dfcb087a277252ace8e292e04f47e953d'}}},
 'location': {'id': 12589342,
  'name': 'Manhattan',
  'slug': 'manhattan-ny',
  'short_name': 'Manhattan, NY',
  'displayable_name': 'Manhattan, NY',
  'localized_name': 'Manhattan',
  'country': 'US',
  'state': 'NY',
  'type': 'County',
  'is_root': False,
  'urls': {'web': {'discover': 'https://www.kickstarter.com/discover/places/manhattan-ny',
    'location': 'https://www.kickstarter.com/locations/manhattan-ny'},
   'api': {'nearby_projects': 'https://api.kickstarter.com/v1/discover?signature=1539904398.aae3553d1e62a16aac55da44ac8c71966f64bb86&woe_id=12589342'}}},
 'category': {'id': 342,
  'name': 'Web',
  'slug': 'technology/web',
  'position': 15,
  'parent_id': 16,
  'color': 6526716,
  'urls': {'web': {'discover': 'http://www.kickstarter.com/discover/categories/technology/web'}}},
 'profile': {'id': 1445394,
  'project_id': 1445394,
  'state': 'inactive',
  'state_changed_at': 1425915879,
  'name': None,
  'blurb': None,
  'background_color': None,
  'text_color': None,
  'link_background_color': None,
  'link_text_color': None,
  'link_text': None,
  'link_url': None,
  'show_feature_image': False,
  'background_image_opacity': 0.8,
  'should_show_feature_image_section': True,
  'feature_image_attributes': {'image_urls': {'default': 'https://ksr-ugc.imgix.net/assets/011/911/160/2ff8292ff8ad7486f38ea865a9c030bb_original.jpg?ixlib=rb-1.1.0&crop=faces&w=1552&h=873&fit=crop&v=1463713991&auto=format&frame=1&q=92&s=f57666c5f7328d47e63f8b389a84bfef',
    'baseball_card': 'https://ksr-ugc.imgix.net/assets/011/911/160/2ff8292ff8ad7486f38ea865a9c030bb_original.jpg?ixlib=rb-1.1.0&crop=faces&w=560&h=315&fit=crop&v=1463713991&auto=format&frame=1&q=92&s=846b5db7dd4a36491881770969721fab'}}},
 'spotlight': False,
 'urls': {'web': {'project': 'https://www.kickstarter.com/projects/joziijobs/jozii-college-jobs-made-easy?ref=category_newest',
   'rewards': 'https://www.kickstarter.com/projects/joziijobs/jozii-college-jobs-made-easy/rewards'}},
 'source_url': 'https://www.kickstarter.com/discover/categories/technology/web'}

In [14]:
# ---- EXTRACT RELEVANT COLUMNS ----
json_obj2[0].keys()

dict_keys(['id', 'photo', 'name', 'blurb', 'goal', 'pledged', 'state', 'slug', 'disable_communication', 'country', 'currency', 'currency_symbol', 'currency_trailing_code', 'deadline', 'state_changed_at', 'created_at', 'launched_at', 'staff_pick', 'is_starrable', 'backers_count', 'static_usd_rate', 'usd_pledged', 'converted_pledged_amount', 'fx_rate', 'current_currency', 'usd_type', 'creator', 'location', 'category', 'profile', 'spotlight', 'urls', 'source_url'])

In [15]:
# Remove probably useless keys as well as and nested-dictionary keys (to be added back later if desired): 
#   - Useless: photo, slug, urls, source_url
#   - Nested: creator, location, category, profile (to maybe be added later)
keys=('id', 'name', 'blurb', 'goal', 'pledged', 'state', 'disable_communication', 'country', 'currency', 'currency_symbol',
      'currency_trailing_code', 'deadline', 'state_changed_at', 'created_at', 'launched_at', 'staff_pick', 'is_starrable',
      'backers_count', 'static_usd_rate', 'usd_pledged', 'converted_pledged_amount', 'fx_rate', 'current_currency', 'usd_type',
      'spotlight')

# pre-allocate
json_obj3 = []
# Append
for x in range(0, len(json_obj2)):
    json_obj3.append({k:json_obj2[x][k] for k in keys})

In [16]:
# ==== ADD BACK USEFUL SUB-DICTIONARY VALUES ====
# Previously removed: 'creator', 'location', 'category', 'profile'

In [17]:
# ---- Explore 'creator' ----

In [18]:
# Grab useful previously removed sub key-value pairs:
json_obj2[0]["creator"].keys()

dict_keys(['id', 'name', 'slug', 'is_registered', 'chosen_currency', 'avatar', 'urls'])

In [19]:
json_obj2[0]["creator"]

{'id': 69089661,
 'name': 'AJ Smith and Brandon Maier (deleted)',
 'slug': 'joziijobs',
 'is_registered': True,
 'chosen_currency': None,
 'avatar': {'thumb': 'https://ksr-ugc.imgix.net/missing_user_avatar.png?ixlib=rb-1.1.0&w=40&h=40&fit=crop&v=&auto=format&frame=1&q=92&s=c8baefb239621e7b5b26957577e078db',
  'small': 'https://ksr-ugc.imgix.net/missing_user_avatar.png?ixlib=rb-1.1.0&w=160&h=160&fit=crop&v=&auto=format&frame=1&q=92&s=fea4448b425bb704dead957d7448b9cc',
  'medium': 'https://ksr-ugc.imgix.net/missing_user_avatar.png?ixlib=rb-1.1.0&w=160&h=160&fit=crop&v=&auto=format&frame=1&q=92&s=fea4448b425bb704dead957d7448b9cc'},
 'urls': {'web': {'user': 'https://www.kickstarter.com/profile/joziijobs'},
  'api': {'user': 'https://api.kickstarter.com/v1/users/69089661?signature=1539920420.2da0e34dfcb087a277252ace8e292e04f47e953d'}}}

In [20]:
# Useful keys are: 'is_registered'

In [25]:
# Add 'is_registered' to json_obj3
for x in range(0, len(json_obj3)):
    json_obj3[x]["creator_registered"] = json_obj2[x]["creator"]["is_registered"]

In [26]:
# ---- Explore 'location' ----

In [27]:
json_obj2[0]["location"].keys()

dict_keys(['id', 'name', 'slug', 'short_name', 'displayable_name', 'localized_name', 'country', 'state', 'type', 'is_root', 'urls'])

In [28]:
json_obj2[0]["location"]

{'id': 12589342,
 'name': 'Manhattan',
 'slug': 'manhattan-ny',
 'short_name': 'Manhattan, NY',
 'displayable_name': 'Manhattan, NY',
 'localized_name': 'Manhattan',
 'country': 'US',
 'state': 'NY',
 'type': 'County',
 'is_root': False,
 'urls': {'web': {'discover': 'https://www.kickstarter.com/discover/places/manhattan-ny',
   'location': 'https://www.kickstarter.com/locations/manhattan-ny'},
  'api': {'nearby_projects': 'https://api.kickstarter.com/v1/discover?signature=1539904398.aae3553d1e62a16aac55da44ac8c71966f64bb86&woe_id=12589342'}}}

In [29]:
# Useful keys: country, state

In [30]:
for x in range(0, len(json_obj3)):
    # Extract country and state data
    if "location" in json_obj2[x]:
        json_obj3[x]["loc_country"] = json_obj2[x]["location"]["country"]
        json_obj3[x]["loc_state"] = json_obj2[x]["location"]["state"]
    # Add NaN when country/state data does not exist
    else:
        json_obj3[x]["loc_country"] = float('NaN')
        json_obj3[x]["loc_state"] = float('NaN')

In [31]:
# ---- Explore 'category' ----

In [32]:
# Grab useful previously removed sub key-value pairs:
json_obj2[0]["category"].keys()

dict_keys(['id', 'name', 'slug', 'position', 'parent_id', 'color', 'urls'])

In [33]:
json_obj2[0]["category"]

{'id': 342,
 'name': 'Web',
 'slug': 'technology/web',
 'position': 15,
 'parent_id': 16,
 'color': 6526716,
 'urls': {'web': {'discover': 'http://www.kickstarter.com/discover/categories/technology/web'}}}

In [34]:
# Useful keys: name, slug, position, parent_id

In [35]:
# Check for null entries
x_category = 0
for x in range(0, len(json_obj2)):
    if "category" in json_obj2[x]:
        x_category = x_category + 1
    else:
        break
x_category - len(json_obj2)

0

In [36]:
json_obj2[0]["category"]

{'id': 342,
 'name': 'Web',
 'slug': 'technology/web',
 'position': 15,
 'parent_id': 16,
 'color': 6526716,
 'urls': {'web': {'discover': 'http://www.kickstarter.com/discover/categories/technology/web'}}}

In [37]:
x_name = 0
for x in range(0, len(json_obj2)):
    if "name" in json_obj2[x]["category"]:
        x_name = x_name + 1
x_name - len(json_obj2)

0

In [38]:
x_slug = 0
for x in range(0, len(json_obj2)):
    if "slug" in json_obj2[x]["category"]:
        x_slug = x_slug + 1
x_slug - len(json_obj2)

0

In [39]:
x_position = 0
for x in range(0, len(json_obj2)):
    if "position" in json_obj2[x]["category"]:
        x_position = x_position + 1
x_position - len(json_obj2)

0

In [40]:
x_parent_id = 0
for x in range(0, len(json_obj2)):
    if "parent_id" in json_obj2[x]["category"]:
        x_parent_id = x_parent_id + 1
x_parent_id - len(json_obj2)

-17378

In [41]:
# NOTE: parent_id has 17378 null values!

In [42]:
for x in range(0, len(json_obj3)):
    # Extract name, slug, position, and parent_id data
    json_obj3[x]["category_name"] = json_obj2[x]["category"]["name"]
    json_obj3[x]["category_slug"] = json_obj2[x]["category"]["slug"]
    json_obj3[x]["category_position"] = json_obj2[x]["category"]["position"]
    if "parent_id" in json_obj2[x]["category"]:
        json_obj3[x]["category_parent_id"] = json_obj2[x]["category"]["parent_id"]
    # Add NaN when data does not exist
    else:
        json_obj3[x]["category_parent_id"] = float('NaN')

In [43]:
json_obj3[0]

{'id': 895922629,
 'name': 'Jozii-College Jobs Made Easy',
 'blurb': 'Jozii is the premier service for full-time university students to find paid part-time work and internships.',
 'goal': 3500,
 'pledged': 50,
 'state': 'failed',
 'disable_communication': False,
 'country': 'US',
 'currency': 'USD',
 'currency_symbol': '$',
 'currency_trailing_code': True,
 'deadline': 1417150740,
 'state_changed_at': 1417150742,
 'created_at': 1413476386,
 'launched_at': 1414525374,
 'staff_pick': False,
 'is_starrable': False,
 'backers_count': 1,
 'static_usd_rate': 1,
 'usd_pledged': '50.0',
 'converted_pledged_amount': 50,
 'fx_rate': 1,
 'current_currency': 'USD',
 'usd_type': 'international',
 'spotlight': False,
 'creator_registered': True,
 'loc_country': 'US',
 'loc_state': 'NY',
 'category_name': 'Web',
 'category_slug': 'technology/web',
 'category_position': 15,
 'category_parent_id': 16}

In [44]:
# ---- Explore 'profile' ----

In [45]:
# Grab useful previously removed sub key-value pairs:
json_obj2[0]["profile"].keys()

dict_keys(['id', 'project_id', 'state', 'state_changed_at', 'name', 'blurb', 'background_color', 'text_color', 'link_background_color', 'link_text_color', 'link_text', 'link_url', 'show_feature_image', 'background_image_opacity', 'should_show_feature_image_section', 'feature_image_attributes'])

In [46]:
json_obj2[56037]["profile"]

{'id': 1841891,
 'project_id': 1841891,
 'state': 'inactive',
 'state_changed_at': 1429068314,
 'name': None,
 'blurb': None,
 'background_color': None,
 'text_color': None,
 'link_background_color': None,
 'link_text_color': None,
 'link_text': None,
 'link_url': None,
 'show_feature_image': False,
 'background_image_opacity': 0.8,
 'should_show_feature_image_section': True,
 'feature_image_attributes': {'image_urls': {'default': 'https://ksr-ugc.imgix.net/assets/012/107/897/fa251d5986d6744d80e917ce8402ae0b_original.jpg?ixlib=rb-1.1.0&crop=faces&w=1552&h=873&fit=crop&v=1463737460&auto=format&frame=1&q=92&s=3417203c5d3a4e034ffc31fa89c1c892',
   'baseball_card': 'https://ksr-ugc.imgix.net/assets/012/107/897/fa251d5986d6744d80e917ce8402ae0b_original.jpg?ixlib=rb-1.1.0&crop=faces&w=560&h=315&fit=crop&v=1463737460&auto=format&frame=1&q=92&s=ddce863a58a3fae73b17d0e6610a85a2'}}}

In [47]:
json_obj2[4]["profile"]["state"]

'active'

In [48]:
# check to see how many profile states are 'inactive'
x_inactive = 0
for x in range(0, len(json_obj2)):
    if json_obj2[x]["profile"]["state"] == 'inactive':
        x_inactive += 1
x_inactive

181513

In [49]:
# check to see how many profile states are 'active'
x_active = 0
for x in range(0, len(json_obj2)):
    if json_obj2[x]["profile"]["state"] == 'active':
        x_active += 1
x_active

24183

In [50]:
len(json_obj2) - x_active - x_inactive

0

In [51]:
# There are only two options for state: active and inactive - there are many inactive profile states

In [52]:
# Useful keys: none
# This is a bit of a guess. Most of the profile states are labeled as 'inactive'.
# My guess is that the profiles go latent once a projct is finished (perhaps regardless of whether it was successful or not)

In [53]:
# ---- CONVERT TO DATA FRAME ----

In [54]:
json_obj3[0]

{'id': 895922629,
 'name': 'Jozii-College Jobs Made Easy',
 'blurb': 'Jozii is the premier service for full-time university students to find paid part-time work and internships.',
 'goal': 3500,
 'pledged': 50,
 'state': 'failed',
 'disable_communication': False,
 'country': 'US',
 'currency': 'USD',
 'currency_symbol': '$',
 'currency_trailing_code': True,
 'deadline': 1417150740,
 'state_changed_at': 1417150742,
 'created_at': 1413476386,
 'launched_at': 1414525374,
 'staff_pick': False,
 'is_starrable': False,
 'backers_count': 1,
 'static_usd_rate': 1,
 'usd_pledged': '50.0',
 'converted_pledged_amount': 50,
 'fx_rate': 1,
 'current_currency': 'USD',
 'usd_type': 'international',
 'spotlight': False,
 'creator_registered': True,
 'loc_country': 'US',
 'loc_state': 'NY',
 'category_name': 'Web',
 'category_slug': 'technology/web',
 'category_position': 15,
 'category_parent_id': 16}

In [55]:
len(json_obj3)

205696

In [56]:
df = pd.DataFrame.from_records(json_obj3)
df.head()

,backers_count,blurb,category_name,category_parent_id,category_position,category_slug,converted_pledged_amount,country,created_at,creator_registered,...,loc_state,name,pledged,spotlight,staff_pick,state,state_changed_at,static_usd_rate,usd_pledged,usd_type
0,1,Jozii is the premier service for full-time uni...,Web,16.0,15,technology/web,50,US,1413476386,True,...,NY,Jozii-College Jobs Made Easy,50.00,False,False,failed,1417150742,1.000000,50.0,international
1,63,Dropsy is an adventure game with a focus on ex...,Video Games,12.0,7,games/video games,1613,US,1317217452,True,...,FL,DROPSY: A different take on the old school adv...,1613.47,True,True,successful,1320259153,1.000000,1613.47,international
2,113,We've bought a press and already found a studi...,Letterpress,18.0,7,publishing/letterpress,6633,US,1403324529,True,...,OR,Letra Chueca / Crooked Letter: a printshop & b...,6633.00,True,False,successful,1410502338,1.000000,6633.0,international
3,1,"Premium, fashion sneaker brand intertwining hi...",Footwear,9.0,5,fashion/footwear,1,GB,1457103832,True,...,England,High End Premium Handmade Sneakers,1.00,False,False,failed,1462305856,1.407899,1.40789944,international
4,99,Made in Europe from the finest quality leather...,Footwear,9.0,5,fashion/footwear,20654,CA,1423776567,True,...,ON,The Domenico Sneakerboot by Luigi Sardo Shoes,25338.00,True,False,successful,1429678899,0.782122,19817.40571572,international

In [57]:
df.tail()

,backers_count,blurb,category_name,category_parent_id,category_position,category_slug,converted_pledged_amount,country,created_at,creator_registered,...,loc_state,name,pledged,spotlight,staff_pick,state,state_changed_at,static_usd_rate,usd_pledged,usd_type
205691,66,Re: Magazine is the Savannah College of Art an...,Periodicals,18.0,10,publishing/periodicals,4846,US,1329261163,True,...,GA,Re: Magazine,4846.79,True,True,successful,1330664342,1.000000,4846.79,international
205692,113,"Due to popularity, demand, and based on feedba...",Events,3.0,3,comics/events,8596,GB,1389612547,True,...,England,Melksham Comic Con 2014 - The Expansion!,5186.50,True,False,successful,1396700229,1.668265,8652.45860083,international
205693,259,An epic and timeless hand illustrated deck of ...,Playing Cards,12.0,4,games/playing cards,7623,US,1409509864,True,...,FL,A Deck of Skeletons. Vintage Playing Cards.,7623.00,True,False,successful,1412891110,1.000000,7623.0,international
205694,2,The slasher film has returned.,Horror,11.0,10,film & video/horror,80,US,1475388732,True,...,OH,I'm Scared - Inde Film,80.00,False,False,failed,1477985542,1.000000,80.0,international
205695,3,We are opening what we hope will be a wonderfu...,Restaurants,10.0,9,food/restaurants,35,US,1405914894,True,...,TX,Get Hula Cowgirl Shaved Ice Over the Last Bump!,35.00,False,False,failed,1408057020,1.000000,35.0,international

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205696 entries, 0 to 205695
Data columns (total 32 columns):
backers_count               205696 non-null int64
blurb                       205696 non-null object
category_name               205696 non-null object
category_parent_id          188318 non-null float64
category_position           205696 non-null int64
category_slug               205696 non-null object
converted_pledged_amount    205696 non-null int64
country                     205696 non-null object
created_at                  205696 non-null int64
creator_registered          205696 non-null bool
currency                    205696 non-null object
currency_symbol             205696 non-null object
currency_trailing_code      205696 non-null bool
current_currency            205696 non-null object
deadline                    205696 non-null int64
disable_communication       205696 non-null bool
fx_rate                     205696 non-null float64
goal                        205696 non-null float64
id                          205696 non-null int64
is_starrable                205696 non-null bool
launched_at                 205696 non-null int64
loc_country                 204404 non-null object
loc_state                   204352 non-null object
name                        205696 non-null object
pledged                     205696 non-null float64
spotlight                   205696 non-null bool
staff_pick                  205696 non-null bool
state                       205696 non-null object
state_changed_at            205696 non-null int64
static_usd_rate             205696 non-null float64
usd_pledged                 205696 non-null object
usd_type                    203968 non-null object
dtypes: bool(6), float64(5), int64(8), object(13)
memory usage: 42.0+ MB

In [59]:
df.describe()

,backers_count,category_parent_id,category_position,converted_pledged_amount,created_at,deadline,fx_rate,goal,id,launched_at,pledged,state_changed_at,static_usd_rate
count,205696.000000,188318.000000,205696.000000,2.056960e+05,2.056960e+05,2.056960e+05,205696.000000,2.056960e+05,2.056960e+05,2.056960e+05,2.056960e+05,2.056960e+05,205696.000000
mean,146.106132,11.782331,7.137514,1.223341e+04,1.412305e+09,1.418814e+09,1.003671,4.513457e+04,1.074607e+09,1.415885e+09,1.373092e+04,1.418616e+09,1.017976
std,1033.317310,5.540618,4.575614,9.256958e+04,7.025463e+07,7.041752e+07,0.197427,1.141468e+06,6.190907e+08,7.056412e+07,1.346135e+05,7.018238e+07,0.201805
min,0.000000,1.000000,1.000000,0.000000e+00,1.240335e+09,1.241334e+09,0.008886,1.000000e-02,1.852000e+04,1.240603e+09,0.000000e+00,1.241334e+09,0.008771
25%,4.000000,10.000000,3.000000,1.100000e+02,1.358319e+09,1.365907e+09,1.000000,1.500000e+03,5.379528e+08,1.363131e+09,1.100000e+02,1.365890e+09,1.000000
50%,27.000000,12.000000,6.000000,1.558000e+03,1.415725e+09,1.423431e+09,1.000000,5.000000e+03,1.077976e+09,1.420672e+09,1.560320e+03,1.423275e+09,1.000000
75%,85.000000,16.000000,10.000000,6.220000e+03,1.463547e+09,1.470328e+09,1.000000,1.340000e+04,1.608983e+09,1.467530e+09,6.300000e+03,1.470191e+09,1.000000
max,105857.000000,26.000000,19.000000,1.026684e+07,1.539821e+09,1.545013e+09,10.268501,1.000000e+08,2.147476e+09,1.539838e+09,2.334387e+07,1.539839e+09,1.716408

In [62]:
# ========================================
# CLEAN DATA
# ========================================

In [63]:
# ---- REARRANGE COLUMNS ----
df.columns

Index(['backers_count', 'blurb', 'category_name', 'category_parent_id',
       'category_position', 'category_slug', 'converted_pledged_amount',
       'country', 'created_at', 'creator_registered', 'currency',
       'currency_symbol', 'currency_trailing_code', 'current_currency',
       'deadline', 'disable_communication', 'fx_rate', 'goal', 'id',
       'is_starrable', 'launched_at', 'loc_country', 'loc_state', 'name',
       'pledged', 'spotlight', 'staff_pick', 'state', 'state_changed_at',
       'static_usd_rate', 'usd_pledged', 'usd_type'],
      dtype='object')

In [64]:
json_obj3[0].keys()

dict_keys(['id', 'name', 'blurb', 'goal', 'pledged', 'state', 'disable_communication', 'country', 'currency', 'currency_symbol', 'currency_trailing_code', 'deadline', 'state_changed_at', 'created_at', 'launched_at', 'staff_pick', 'is_starrable', 'backers_count', 'static_usd_rate', 'usd_pledged', 'converted_pledged_amount', 'fx_rate', 'current_currency', 'usd_type', 'spotlight', 'creator_registered', 'loc_country', 'loc_state', 'category_name', 'category_slug', 'category_position', 'category_parent_id'])

In [ ]:
# The df keys got rearranged into alphabetical order.

In [65]:
# Re-order columns
df = df[['id', 'name', 'blurb', 'category_name', 'category_slug', 'category_position', 'category_parent_id', 'goal', 'pledged', 
         'disable_communication', 'loc_country', 'loc_state', 'country', 'currency', 'currency_symbol', 'currency_trailing_code', 'deadline', 
         'state_changed_at', 'created_at', 'launched_at', 'staff_pick', 'is_starrable', 'backers_count', 'static_usd_rate', 
         'usd_pledged', 'converted_pledged_amount', 'fx_rate', 'current_currency', 'usd_type', 'spotlight', 
         'creator_registered', 'state']]

In [66]:
df.columns

Index(['id', 'name', 'blurb', 'category_name', 'category_slug',
       'category_position', 'category_parent_id', 'goal', 'pledged',
       'disable_communication', 'loc_country', 'loc_state', 'country',
       'currency', 'currency_symbol', 'currency_trailing_code', 'deadline',
       'state_changed_at', 'created_at', 'launched_at', 'staff_pick',
       'is_starrable', 'backers_count', 'static_usd_rate', 'usd_pledged',
       'converted_pledged_amount', 'fx_rate', 'current_currency', 'usd_type',
       'spotlight', 'creator_registered', 'state'],
      dtype='object')

In [67]:
len(df.columns)

32

In [68]:
# ---- REMOVE DUPLICATES ----

In [69]:
df.sort_values(by=["backers_count"],ascending=False)[["id","name","backers_count"]]

,id,name,backers_count
69279,557230947,"Bring Reading Rainbow Back for Every Child, Ev...",105857
188496,557230947,"Bring Reading Rainbow Back for Every Child, Ev...",105857
150213,1755266685,The Veronica Mars Movie Project,91585
13732,1929840910,Double Fine Adventure,87142
53281,1929840910,Double Fine Adventure,87142
129025,286165030,Torment: Tides of Numenera,74405
136791,286165030,Torment: Tides of Numenera,74405
186022,458565935,Project Eternity,73986
141451,458565935,Project Eternity,73986
174366,1194278206,Yooka-Laylee - A 3D Platformer Rare-vival!,73206
114940,947809001,Shenmue 3,69320
150531,506924864,Pebble: E-Paper Watch for iPhone and Android,68929
80539,506924864,Pebble: E-Paper Watch for iPhone and Android,68929
72627,564596765,Mighty No. 9,67226
78658,1074800880,Bloodstained: Ritual of the Night,64867
179857,1033978702,OUYA: A New Kind of Video Game Console,63416
183540,1033978702,OUYA: A New Kind of Video Game Console,63416
75344,2000827215,Wasteland 2,61290
173782,2000827215,Wasteland 2,61290
68972,1454565733,Bring Back MYSTERY SCIENCE THEATER 3000,48270
156706,1871494789,WISH I WAS HERE,46520
23258,1957695328,Planetary Annihilation - A Next Generation RTS,44162
48858,1957695328,Planetary Annihilation - A Next Generation RTS,44162
67661,275698538,Divinity: Original Sin 2,42713
179190,474183945,BATTLETECH,41733
108310,1552929469,CHIP - The World's First Nine Dollar Computer,39560
110161,577817754,"PINE A64, First $15 64-Bit Single Board Super ...",36781
44394,531044328,Shadowrun Returns,36276
39514,531044328,Shadowrun Returns,36276
136348,1918188380,Font Awesome 5,35550
...,...,...,...
52091,135415487,Mammilaki Handcrafted wooden sunglasses (Cance...,0
52093,1820151576,BACON!!,0
52096,712810035,BATTLEGROUNDS COMP 2014,0
52098,734086209,Not The Birds!,0
170785,1928050075,Cindos Quilts,0
110979,1933964213,"Honest, Equitable, and Balanced News Channel.",0
110969,173301675,"Tartarus, Fall of an Empire",0
189367,820992510,Hair Booth,0
111029,390692844,#crimetag,0
170772,1214372847,Luxe Bracelets,0
111043,1058499667,Rise To The Prize! (Game Show),0
111044,1572774173,PremierThreadsCompany,0
189416,1948581729,A Haunted Hangover,0
111092,2053754055,The Consuela Show!,0
170748,171033191,BORDERED BOTTLES,0
111087,1003366986,SOMASOL Vegan Balms Production Space (Canceled),0
51972,431328886,LOTUS Life Learning - Personal Empowerment for...,0
51975,712996656,Free Wind Chime Designs and Commissions,0
111078,1623243897,Less Than Three (<3),0
111075,1180975882,Portal to Alaska,0
111074,1871460841,Book VS Cover (Canceled),0
111065,917876122,All Things Cryptocurrency - ATC,0
111058,2005180407,T.S. Teens,0
111049,2026472919,Allergist on Demand (Canceled),0
52016,1572474304,FIRE EXPLORER,0
52019,773491825,Cop filming,0
111048,1510249869,Professor Byers Elixirs & Balms,0
52023,1726689593,kush kid collectiblez is a clothing line for t...,0
52029,519956154,Anyone Can Be An Astronaut; Summer Collection,0
41874,1987095871,Au Solar,0

In [70]:
df.drop_duplicates(inplace=True)

In [71]:
df.shape

(189240, 32)

In [72]:
# We dropped 205696-189240=16456 duplicate rows

In [73]:
# Search for more duplicates
len(df["id"].unique()) - len(df)

-2166

In [74]:
# There are still 2166 duplicate IDs

In [75]:
# Explore the duplicate ID rows
pd.concat(g for _, g in df.groupby("id") if len(g) > 1)

,id,name,blurb,category_name,category_slug,category_position,category_parent_id,goal,pledged,disable_communication,...,backers_count,static_usd_rate,usd_pledged,converted_pledged_amount,fx_rate,current_currency,usd_type,spotlight,creator_registered,state
10531,422207,The Arduino Compatible Educational Sensor Lear...,This arduino / Raspberry Pi compatible board s...,Hardware,technology/hardware,8,16.0,1200.0,7728.00,False,...,180,0.911649,7045.22602224,6951,0.771892,USD,international,True,True,successful
69099,422207,The Arduino Compatible Educational Sensor Lear...,This arduino / Raspberry Pi compatible board s...,Hardware,technology/hardware,8,16.0,1200.0,7728.00,False,...,180,0.911649,7045.22602224,6951,0.766650,USD,international,True,True,successful
184333,1033120,Fields of Fire: Miniatures rules for modern co...,"With this simple, yet realistic rules compilat...",Tabletop Games,games/tabletop games,6,12.0,2500.0,2575.00,False,...,35,1.000000,2575.0,2575,1.000000,USD,international,True,True,successful
204054,1033120,Fields of Fire: Miniatures rules for modern co...,"With this simple, yet realistic rules compilat...",Tabletop Games,games/tabletop games,6,12.0,2500.0,2575.00,False,...,35,1.000000,2575.0,3358,1.304376,CAD,None,True,True,successful
83960,2705005,"LOVE MEI waterproof case, protect iPhone X/Xs ...","This IP68 Waterproof Case for iPhone X/Xs, wit...",Gadgets,technology/gadgets,7,16.0,24000.0,1110.00,False,...,11,0.128052,142.1373093,141,0.127570,USD,international,False,True,live
203854,2705005,"LOVE MEI waterproof case, protect iPhone X/Xs ...","This IP68 Waterproof Case for iPhone X/Xs, wit...",Gadgets,technology/gadgets,7,16.0,24000.0,1110.00,False,...,11,0.128006,142.0867266,141,0.127570,USD,international,False,True,live
67679,4534946,'Skin Walkers' knit FMP,I'm a third year student currently designing &...,Couture,fashion/couture,4,9.0,50.0,85.00,False,...,6,1.683130,143.06609165,144,1.317483,USD,international,True,True,successful
160239,4534946,'Skin Walkers' knit FMP,I'm a third year student currently designing &...,Couture,fashion/couture,4,9.0,50.0,85.00,False,...,6,1.683130,143.06609165,145,1.708667,CAD,None,True,True,successful
84917,5090855,Charmed Flying Broom,A spooky horror Halloween old school 3D platfo...,Video Games,games/video games,7,12.0,250000.0,418.80,False,...,2,0.053033,22.210417236,22,0.052969,USD,domestic,False,True,live
105652,5090855,Charmed Flying Broom,A spooky horror Halloween old school 3D platfo...,Video Games,games/video games,7,12.0,250000.0,418.80,False,...,2,0.053033,22.210417236,33,0.080902,NZD,None,False,True,live
27985,5353475,Race the Sun - An Infinite Speed Experience,Intense racing through infinite sandbox worlds...,Video Games,games/video games,7,12.0,20000.0,21579.48,False,...,1144,1.000000,21579.48,21579,1.000000,USD,international,True,True,successful
162084,5353475,Race the Sun - An Infinite Speed Experience,Intense racing through infinite sandbox worlds...,Video Games,games/video games,7,12.0,20000.0,21579.48,False,...,1144,1.000000,21579.48,28147,1.304376,CAD,None,True,True,successful
64961,5780295,Refrigerator Simulator,A quirky mobile puzzle game where you play wit...,Mobile Games,games/mobile games,3,12.0,2500.0,526.00,False,...,25,1.000000,526.0,526,1.000000,USD,international,False,True,live
121955,5780295,Refrigerator Simulator,A quirky mobile puzzle game where you play wit...,Mobile Games,games/mobile games,3,12.0,2500.0,526.00,False,...,25,1.000000,526.0,526,1.000000,USD,domestic,False,True,live
171904,8412272,The ultimate music performance machine for stu...,Pipes is a new audio platform which out-horsep...,Hardware,technology/hardware,8,16.0,100000.0,106609.00,False,...,243,1.000000,106609.0,106609,1.000000,USD,international,False,True,live
205007,8412272,The ultimate music performance machine for stu...,Pipes is a new audio platform which out-horsep...,Hardware,technology/hardware,8,16.0,100000.0,107407.00,False,...,245,1.000000,107407.0,107407,1.000000,USD,international,False,True,live
72812,8688135,QU3UE AN ESPORTS PARADISE,"QU3UE is creating a 10,000 sq. ft. esports fac...",Live Games,games/live games,2,12.0,125000.0,6834.00,False,...,34,1.000000,6834.0,6834,1.000000,USD,international,False,True,live
106469,8688135,QU3UE AN ESPORTS PARADISE,"QU3UE is creating a 10,000 sq. ft. esports fac...",Live Games,games/live games,2,12.0,125000.0,6834.00,False,...,34,1.000000,6834.0,6834,1.000000,USD,domestic,False,True,live
52566,8747999,Soul Entendre: LAUNCH COLLECTION | Streetwear ...,"Quality (Made in the USA), comfortable, and ey...",Apparel,fashion/apparel,2,9.0,5000.0,6963.00,False,...,81,1.000000,6963.0,9082,1.304376,CAD,None,True,True,successful
95609,8747999,Soul Entendre: LAUNCH COLLECTION | Streetwear ...,"Quality (Made in the USA), comfortable, and ey...",Apparel,fashion/apparel,2,9.0,5000.0,6963.00,False,...,81,1.000000,6963.0,6963,1.000000,USD,international,True,True,successful
1030,9888853,Watch Your Mouth ... And Throw An F-Bomb,This is the launch of a new item to help grow ...,Crochet,crafts/crochet,2,26.0,100.0,935.00,False,...,33,0.732279,684.68072475,692,0.771892,USD,international,True,True,successful
83031,9888853,Watch Your Mouth ... And Throw An F-Bomb,This is the launch of a new item to help grow ...,Crochet,crafts/crochet,2,26.0,100.0,935.00,False,...,33,0.732279,684.68072475,692,0.766650,USD,international,True,True,successful
40734,12803820,Going International - Global Fashion Expedition,"A documentary consisting of various events, un...",People,photography/people,4,15.0,1000.0,1005.00,False,...,17,0.915599,920.17714575,922,0.766650,USD,international,True,True,successful
191650,12803820,Going International - Global Fashion Expedition,"A documentary consisting of various events, un...",People,photography/people,4,15.0,1000.0,1005.00,False,...,17,0.915599,920.17714575,922,0.771892,USD,international,True,True,successful
105318,13539350,GodFire Apparel : You have a story. We have a ...,Apparel that gives back and shares incredible ...,Apparel,fashion/apparel,2,9.0,10000.0,10981.00,False,...,116,1.000000,10981.0,10981,1.000000,USD,international,True,True,successful
160257,13539350,GodFire Apparel : You have a story. We have a ...,Apparel that gives back and shares incredible ...,Apparel,fashion/apparel,2,9.0,10000.0,10981.00,False,...,116,1.000000,10981.0,14323,1.304376,CAD,None,True,True,successful
65687,14064883,Wild Assent - Survive the Arena and Tame the W...,A 1-4 player board game with solo/cooperative ...,Tabletop Games,games/tabletop games,6,12.0,70000.0,253377.00,False,...,1612,1.000000,253377.0,253377,1.000000,USD,domestic,False,True,live
91937,14064883,Wild Assent - Survive the Arena and Tame the W...,A 1-4 player board game with solo/cooperative ...,Tabletop Games,games/tabletop games,6,12.0,70000.0,254472.00,False,...,1619,1.000000,254472.0,254472,1.000000,USD,international,False,True,live
24068,15036961,Vortex: A handmade glass collection.,A collection of handmade glass vases and sea s...,Glass,crafts/glass,5,26.0,500.0,2317.00,False,...,47,1.377997,3192.81897949,3142,1.309950,USD,international,True,True,successful
181754,15036961,Vortex: A handmade glass collection.,A collection of handmade glass vases and sea s...,Glass,crafts/glass,5,26.0,500.0,2317.00,False,...,47,1.377997,3192.81897949,3142,1.317483,USD,international,True,True,successful
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204157,2133187312,Mana Crypt,"Venture into the Crypt. Build a deck, bury you...",Tabletop Games,games/tabletop games,6,12.0,3000.0,2243.00,False,...,81,1.000000,2243.0,2243,1.000000,USD,domestic,False,True,live
205551,2133187312,Mana Crypt,"Venture into the Crypt. Build a deck, bury you...",Tabletop Games,games/tabletop games,6,12.0,3000.0,2243.00,False,...,81,1.000000,2243.0,2243,1.000000,USD,international,False,True,live
18192,2133832079,Final Element the Video Game,Think Megaman X meets Metal Slug meets Turtles...,Video Games,games/video games,7,12.0,1000.0,1664.00,False,...,159,1.000000,1664.0,2170,1.304376,CAD,None,True,True,successful
198665,2133832079,Final Element the Video Game,Think Megaman X meets Metal Slug meets Turtles...,Video Games,games/video games,7,12.0,1000.0,1664.00,False,...,159,1.000000,1664.0,1664,1.000000,USD,international,True,True,successful
29566,2134104708,Curvy Cosplay: Custom Patterns & Costumes for ...,Custom drafted patterns and costumes made for ...,Couture,fashion/couture,4,9.0,2000.0,2127.00,False,...,29,1.000000,2127.0,2127,1.000000,USD,international,True,True,successful
179553,2134104708,Curvy Cosplay: Custom Patterns & Costumes for ...,Custom drafted patterns and costumes made for ...,Couture,fashion/couture,4,9.0,2000.0,2127.00,False,...,29,1.000000,2127.0,2774,1.304376,CAD,None,True,True,successful
79533,2137724959,Empower Arts Magazine: Celebrating the healing...,Empower Arts is a publication dedicated to tel...,Periodicals,publishing/periodicals,10,18.0,500.0,1082.00,False,...,38,1.293214,1399.25794834,1417,1.309950,USD,international,False,True,live
159346,2137724959,Empower Arts Magazine: Celebrating the healing...,Empower Arts is a publication dedicated to tel...,Periodicals,publishing/periodicals,10,18.0,500.0,1082.00,False,...,38,1.293214,1399.25794834,1425,1.317483,USD,international,False,True,live
13940,2137727326,The Production Studio,The Production Studio is looking to become a l...,Fine Art,photography/fine art,2,15.0,3000.0,3451.00,False,...,11,0.786033,2712.60033163,2627,0.766650,USD,international,True,True,successful
85826,2137727326,The Production Studio,The Production Studio is looking to become a l...,Fine Art,photography/fine art,2,15.0,3000.0,3451.00,False,...,11,0.786033,2712.60033163,2627,0.771892,USD,international,True,True,successful
33248,2137911646,Hora Azulona,Porque Getafe tiene afición y hacemos radio pa...,Audio,journalism/audio,1,13.0,600.0,1304.00,False,...,30,1.096596,1429.96097536,1461,1.149996,USD,international,True,True,successful
190799,2137911646,Hora Azulona,Porque Getafe tiene afición y hacemos radio pa...,Audio,journalism/audio,1,13.0,600.0,1304.00,False,...,30,1.096596,1429.96097536,1461,1.156109,USD,international,True,True,successful
64796,2138176669,Something Terrible: An Exercise in Inadequacy,A callback to the Atari age of gaming; when th...,Video Games,games/video games,7,12.0,113.0,12.29,False,...,9,0.774260,9.5156539252,9,0.771892,USD,international,False,True,live
96690,2138176669,Something Terrible: An Exercise in Inadequacy,A callback to the Atari age of gaming; when th...,Video Games,games/video games,7,12.0,113.0,12.29,False,...,9,0.774260,9.5156539252,9,0.766650,USD,international,False,True,live
187107,2141207772,Gnomes at Midnight,"A 2-player, light strategy, kind-hearted, fun ...",Tabletop Games,games/tabletop games,6,12.0,12750.0,3339.29,False,...,76,0.766960,2561.1017916142,20067,6.009655,HKD,None,False,True,live
193423,2141207772,Gnomes at Midnight,"A 2-player, light strategy, kind-hearted, fun ...",Tabletop Games,games/tabletop games,6,12.0,12750.0,3339.29,False,...,76,0.766960,2561.1017916142,1954,0.585251,GBP,None,False,True,live
15320,2141519698,CharlieYipBrand: Minimalist Leather Wallets & ...,This project aims towards the functionality of...,Accessories,fashion/accessories,1,9.0,2500.0,2592.00,False,...,57,1.000000,2592.0,3380,1.304376,CAD,None,True,True,successful
166362,2141519698,CharlieYipBrand: Minimalist Leather Wallets & ...,This project aims towards the functionality of...,Accessories,fashion/accessories,1,9.0,2500.0,2592.00,False,...,57,1.000000,2592.0,2592,1.000000,USD,international,True,True,successful
21482,2142171940,"HDMIPi Affordable 9"" High-Def screen for the R...",Small HDMI screens are expensive. Native HD o...,Hardware,technology/hardware,8,16.0,55000.0,261250.46,False,...,2523,1.603600,418941.1749558896,427644,1.309950,USD,international,True,True,successful
25143,2142171940,"HDMIPi Affordable 9"" High-Def screen for the R...",Small HDMI screens are expensive. Native HD o...,Hardware,technology/hardware,8,16.0,55000.0,261250.46,False,...,2523,1.603600,418941.1749558896,427644,1.317483,USD,international,True,True,successful
119055,2142218219,Quopener - The new effortless way to open jars,It's never been easier to open jars. With the ...,Product Design,design/product design,5,7.0,60000.0,5220.00,False,...,118,1.156470,6036.775749,6002,1.149996,USD,domestic,False,True,live
191184,2142218219,Quopener - The new effortless way to open jars,It's never been easier to open jars. With the ...,Product Design,design/product design,5,7.0,60000.0,5220.00,False,...,118,1.156470,6036.775749,6002,1.149996,USD,international,False,True,live
105159,2144192426,THRESHOLD: ALLURE,Threshold returns! Introducing Praxi!,Comic Books,comics/comic books,2,3.0,1800.0,8698.00,False,...,115,1.000000,8698.0,8698,1.000000,USD,international,False,True,live
163626,2144192426,THRESHOLD: ALLURE,Threshold returns! Introducing Praxi!,Comic Books,comics/comic books,2,3.0,1800.0,8734.00,False,...,117,1.000000,8734.0,8734,1.000000,USD,international,False,True,live
2973,2144932149,Create personalized boutique-quality jewelry!,Create wearable memories with affordable jewel...,Jewelry,fashion/jewelry,6,9.0,25000.0,25766.00,False,...,189,1.000000,25766.0,33608,1.304376,CAD,None,True,True,successful
100227,2144932149,Create personalized boutique-quality jewelry!,Create wearable memories with affordable jewel...,Jewelry,fashion/jewelry,6,9.0,25000.0,25766.00,False,...,189,1.000000,25766.0,25766,1.000000,USD,international,True,True,successful
59526,2146692994,Anne Fogarty: Buy a Dress Bring Back a Fashion...,After 34 years the Anne Fogarty label is back....,Apparel,fashion/apparel,2,9.0,30000.0,30062.00,False,...,90,1.000000,30062.0,39212,1.304376,CAD,None,True,True,successful
133960,2146692994,Anne Fogarty: Buy a Dress Bring Back a Fashion...,After 34 years the Anne Fogarty label is back....,Apparel,fashion/apparel,2,9.0,30000.0,30062.00,False,...,90,1.000000,30062.0,30062,1.000000,USD,international,True,True,successful
168921,2147339483,Movema Dance Studio,"With your support, Movema can relocate to offi...",Spaces,dance/spaces,3,6.0,3000.0,3320.00,False,...,56,1.412765,4690.3785052,4793,1.317483,USD,international,True,True,successful
178641,2147339483,Movema Dance Studio,"With your support, Movema can relocate to offi...",Spaces,dance/spaces,3,6.0,3000.0,3320.00,False,...,56,1.412765,4690.3785052,4793,1.309950,USD,international,True,True,successful

In [76]:
# It looks like some of the rows look different due to usd_pledged, converted_pledged_amount, fx_rate (which appears to be 
# exchange rate), and current_currency. Let's just delete the following currency-related columns:
# currency_symbol, static_usd_rate, convertd_pledged_amount, fx_rate, current_currency, usd_type
df.drop(columns=['currency_symbol','static_usd_rate','converted_pledged_amount','fx_rate','current_currency','usd_type'], 
        inplace=True)

In [77]:
df.shape

(189240, 26)

In [78]:
df.columns

Index(['id', 'name', 'blurb', 'category_name', 'category_slug',
       'category_position', 'category_parent_id', 'goal', 'pledged',
       'disable_communication', 'loc_country', 'loc_state', 'country',
       'currency', 'currency_trailing_code', 'deadline', 'state_changed_at',
       'created_at', 'launched_at', 'staff_pick', 'is_starrable',
       'backers_count', 'usd_pledged', 'spotlight', 'creator_registered',
       'state'],
      dtype='object')

In [79]:
df.drop_duplicates(inplace=True)

In [80]:
df.shape

(187367, 26)

In [81]:
# We dropped 189240-187367=1873 duplicate rows

In [82]:
# Search for more duplicates
len(df["id"].unique()) - len(df)

-293

In [83]:
# There are still 293 duplicate ID rows

In [84]:
pd.options.display.max_columns = None

In [85]:
df.loc[[171904,205007]]

,id,name,blurb,category_name,category_slug,category_position,category_parent_id,goal,pledged,disable_communication,loc_country,loc_state,country,currency,currency_trailing_code,deadline,state_changed_at,created_at,launched_at,staff_pick,is_starrable,backers_count,usd_pledged,spotlight,creator_registered,state
171904,8412272,The ultimate music performance machine for stu...,Pipes is a new audio platform which out-horsep...,Hardware,technology/hardware,8,16.0,100000.0,106609.0,False,US,CA,US,USD,True,1542234085,1539638486,1537803552,1539638485,True,True,243,106609.0,False,True,live
205007,8412272,The ultimate music performance machine for stu...,Pipes is a new audio platform which out-horsep...,Hardware,technology/hardware,8,16.0,100000.0,107407.0,False,US,CA,US,USD,True,1542234085,1539638486,1537803552,1539638485,True,True,245,107407.0,False,True,live

In [154]:
# It looks like there are differences with pledged, backers_count and usd_pledged

In [86]:
# usd_pledged is redundant with pledged - remove usd_pledged
df.drop(columns=['usd_pledged'], inplace=True)

In [87]:
df.shape

(187367, 25)

In [88]:
df.drop_duplicates(inplace=True)

In [89]:
df.shape

(187345, 25)

In [90]:
# we dropped 187367-187345=22 duplicate rows

In [91]:
# Search for more duplicates
len(df["id"].unique()) - len(df)

-271

In [92]:
# There are still 271 duplicates

In [93]:
# is_starrable is unclear and seems to be a problem with duplicates. Let's drop it
df.drop(columns=['is_starrable'], inplace=True)

In [94]:
df.shape

(187345, 24)

In [95]:
df.drop_duplicates(inplace=True)

In [96]:
df.shape

(187344, 24)

In [97]:
# Search for more duplicates
len(df["id"].unique()) - len(df)

-270

In [199]:
# There are still 270 duplicates

In [98]:
df.loc[[171904,205007]]

,id,name,blurb,category_name,category_slug,category_position,category_parent_id,goal,pledged,disable_communication,loc_country,loc_state,country,currency,currency_trailing_code,deadline,state_changed_at,created_at,launched_at,staff_pick,backers_count,spotlight,creator_registered,state
171904,8412272,The ultimate music performance machine for stu...,Pipes is a new audio platform which out-horsep...,Hardware,technology/hardware,8,16.0,100000.0,106609.0,False,US,CA,US,USD,True,1542234085,1539638486,1537803552,1539638485,True,243,False,True,live
205007,8412272,The ultimate music performance machine for stu...,Pipes is a new audio platform which out-horsep...,Hardware,technology/hardware,8,16.0,100000.0,107407.0,False,US,CA,US,USD,True,1542234085,1539638486,1537803552,1539638485,True,245,False,True,live

In [101]:
# Still differences between pledged and backers_count. Without some sort of a time stamp we don't know which one is the most
# updated row. Let's look for duplicate IDs, then keep the rows with the largest pledge values

In [102]:
df = df.sort_values('pledged', ascending=False).drop_duplicates('id').sort_index()

In [100]:
df.loc[df["id"] == 8412272].pledged

205007    107407.0
Name: pledged, dtype: float64

In [235]:
# Looks like it worked! There is only one entry for ID 8412272 and it is the larger pledge of the two initial entries.

In [108]:
# Search for more duplicates
len(df["id"].unique()) - len(df)

0

In [109]:
# No more duplicates!

In [110]:
df.shape

(187074, 24)

In [111]:
df.columns

Index(['id', 'name', 'blurb', 'category_name', 'category_slug',
       'category_position', 'category_parent_id', 'goal', 'pledged',
       'disable_communication', 'loc_country', 'loc_state', 'country',
       'currency', 'currency_trailing_code', 'deadline', 'state_changed_at',
       'created_at', 'launched_at', 'staff_pick', 'backers_count', 'spotlight',
       'creator_registered', 'state'],
      dtype='object')

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 187074 entries, 0 to 205695
Data columns (total 24 columns):
id                        187074 non-null int64
name                      187074 non-null object
blurb                     187074 non-null object
category_name             187074 non-null object
category_slug             187074 non-null object
category_position         187074 non-null int64
category_parent_id        169696 non-null float64
goal                      187074 non-null float64
pledged                   187074 non-null float64
disable_communication     187074 non-null bool
loc_country               186198 non-null object
loc_state                 186155 non-null object
country                   187074 non-null object
currency                  187074 non-null object
currency_trailing_code    187074 non-null bool
deadline                  187074 non-null int64
state_changed_at          187074 non-null int64
created_at                187074 non-null int64
launched_at               187074 non-null int64
staff_pick                187074 non-null bool
backers_count             187074 non-null int64
spotlight                 187074 non-null bool
creator_registered        187074 non-null bool
state                     187074 non-null object
dtypes: bool(5), float64(3), int64(7), object(9)
memory usage: 34.4+ MB

In [117]:
# Re-index
df.reset_index(drop=True, inplace=True)

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187074 entries, 0 to 187073
Data columns (total 24 columns):
id                        187074 non-null int64
name                      187074 non-null object
blurb                     187074 non-null object
category_name             187074 non-null object
category_slug             187074 non-null object
category_position         187074 non-null int64
category_parent_id        169696 non-null float64
goal                      187074 non-null float64
pledged                   187074 non-null float64
disable_communication     187074 non-null bool
loc_country               186198 non-null object
loc_state                 186155 non-null object
country                   187074 non-null object
currency                  187074 non-null object
currency_trailing_code    187074 non-null bool
deadline                  187074 non-null int64
state_changed_at          187074 non-null int64
created_at                187074 non-null int64
launched_at               187074 non-null int64
staff_pick                187074 non-null bool
backers_count             187074 non-null int64
spotlight                 187074 non-null bool
creator_registered        187074 non-null bool
state                     187074 non-null object
dtypes: bool(5), float64(3), int64(7), object(9)
memory usage: 28.0+ MB

In [ ]:
df.to_csv('analysis.csv', sep=',')

In [261]:
# ---- FURTHER REFINE VARIABLES ----

In [125]:
df.columns

Index(['id', 'name', 'blurb', 'category_name', 'category_slug',
       'category_position', 'category_parent_id', 'goal', 'pledged',
       'disable_communication', 'loc_country', 'loc_state', 'country',
       'currency', 'currency_trailing_code', 'deadline', 'state_changed_at',
       'created_at', 'launched_at', 'staff_pick', 'backers_count', 'spotlight',
       'creator_registered', 'state'],
      dtype='object')

# variable notes

## delete
* blurb - delete
* loc_state - delete (too granular)
* country - delete (not sure how it differs from loc_country; largely redundant)
* currency - delete (pledges is in usd)
* currency_trailing_code - delete (what is it?)
* state_changed_at - delete

## keep
* id - keep (primary key)
* name - keep (for reference)
* category_name - keep; change to sub_category
* category slug - keep; extract first word; change to category
* category_position - keep; change to sub_category_id; move before sub_category
* category_parent_id - keep; change to category_id; move before category
* goal - keep
* pledged - keep
* disable_communication - keep (but what is it??)
* loc_country - keep (where the project is launche from); rename as country
* deadline - keep; convert to datetime
* created_at - keep; convert to datetime
* launched_at - keep; convert to datetime
* staff_pick - keep
* backers_count - keep; move before pledged
* spotlight - keep (but what is it?)
* creator_registered - keep
* state - keep

In [130]:
df.drop(columns=['blurb','loc_state','country','currency','currency_trailing_code','state_changed_at'], inplace=True)

In [133]:
len(df.columns)

18

In [136]:
# Rename columns
df.rename(columns={'category_name':'sub_category', 'category_slug':'category', 'category_position':'sub_category_id', 
                  'category_parent_id':'category_id', 'loc_country':'country', 'state':'launch_state'}, inplace=True)

In [138]:
df.columns

Index(['id', 'name', 'sub_category', 'category', 'sub_category_id',
       'category_id', 'goal', 'pledged', 'disable_communication', 'country',
       'deadline', 'created_at', 'launched_at', 'staff_pick', 'backers_count',
       'spotlight', 'creator_registered', 'launch_state'],
      dtype='object')

In [139]:
# Re-arrange columns
df = df[['id', 'name', 'sub_category_id', 'sub_category', 'category_id', 'category', 'goal', 'backers_count', 'pledged', 
         'disable_communication', 'country','deadline', 'created_at', 'launched_at', 'staff_pick', 'spotlight', 
         'creator_registered', 'launch_state']]

In [140]:
df.columns

Index(['id', 'name', 'sub_category_id', 'sub_category', 'category_id',
       'category', 'goal', 'backers_count', 'pledged', 'disable_communication',
       'country', 'deadline', 'created_at', 'launched_at', 'staff_pick',
       'spotlight', 'creator_registered', 'launch_state'],
      dtype='object')

In [144]:
df.sort_values(by=['category_id','sub_category_id'])

,id,name,sub_category_id,sub_category,category_id,category,goal,backers_count,pledged,disable_communication,country,deadline,created_at,launched_at,staff_pick,spotlight,creator_registered,launch_state
203,710268515,Decker-Smith Pottery Returns!,1,Ceramics,1.0,art/ceramics,2425.00,103,7550.00,False,US,1425855600,1424404478,1424460276,True,True,True,successful
221,367139629,One Piece fan.. full collection!,1,Ceramics,1.0,art/ceramics,85.00,0,0.00,False,BE,1442427120,1439830504,1439835120,False,False,True,failed
237,2144529772,WilcoxsonBrooklynCeramics,1,Ceramics,1.0,art/ceramics,20000.00,9,276.00,False,US,1452962031,1449592381,1450370031,False,False,True,failed
252,703029125,Personalised & Hand-glazed ceramics.,1,Ceramics,1.0,art/ceramics,4500.00,23,533.00,False,GB,1501579528,1495788869,1498987528,False,False,True,failed
456,1480803309,A Commemorative Beer Stein - Inspired by Brett...,1,Ceramics,1.0,art/ceramics,10000.00,12,384.00,False,US,1541032247,1538439659,1538675280,False,False,True,live
481,1455271842,BRICK Ceramics Studio Opening!,1,Ceramics,1.0,art/ceramics,15000.00,119,15299.00,False,US,1430981940,1423575259,1428320006,False,True,True,successful
519,1460620306,Alisha's Pottery Studio,1,Ceramics,1.0,art/ceramics,700.00,8,345.00,False,US,1448156043,1443735046,1445560443,False,False,True,failed
627,995319524,JUMPING CREEK POTTERY STUDIO EXPANSION,1,Ceramics,1.0,art/ceramics,25000.00,215,26229.00,False,CA,1426120620,1422502366,1423532220,True,True,True,successful
649,2111622512,Michelle Dziadkowicz Ceramics Studio - A place...,1,Ceramics,1.0,art/ceramics,30000.00,14,1775.00,False,US,1431759540,1426282073,1426612843,False,False,True,canceled
658,829968813,Launching BK Clay Cafe In 60 Days + Coffee Hou...,1,Ceramics,1.0,art/ceramics,3000.00,8,482.00,False,US,1413202144,1409803618,1410610144,False,False,True,failed
1686,80929331,MENEO,1,Ceramics,1.0,art/ceramics,15000.00,13,7660.00,False,MX,1500062400,1496704185,1497978699,False,False,True,failed
1725,1564541619,Clay Art Commissions. Collaborate with potters...,1,Ceramics,1.0,art/ceramics,2500.00,14,2520.00,False,US,1513651578,1509581782,1511923578,False,True,True,successful
1735,1570668135,"Help The Village Potters build a ""Kazegama"" Kiln",1,Ceramics,1.0,art/ceramics,14000.00,42,2580.00,False,US,1436500800,1433159730,1433876064,False,False,True,failed
1774,2091945557,sub,1,Ceramics,1.0,art/ceramics,5100.00,0,0.00,False,NL,1419807600,1415711758,1417518654,False,False,True,failed
1775,2073905425,Marina Del Clay,1,Ceramics,1.0,art/ceramics,9999.00,39,4642.00,False,US,1541804214,1536667111,1539208614,False,False,True,live
1871,1614827978,PAWfect Paintings Pottery Expansion,1,Ceramics,1.0,art/ceramics,1000.00,3,52.00,False,US,1458672115,1456076373,1456083715,False,False,True,failed
1894,472119134,byebyebirdy,1,Ceramics,1.0,art/ceramics,1000.00,3,48.00,False,GB,1496190338,1493062884,1493598338,False,False,True,failed
1915,1079930054,VESU Ceramic Travel Mugs,1,Ceramics,1.0,art/ceramics,12000.00,15,638.00,False,US,1513378815,1504540231,1508191215,False,False,True,failed
1922,1083652867,EricSSLeaPottery Pottery Ceramics (Canceled),1,Ceramics,1.0,art/ceramics,1500.00,0,0.00,False,US,1463343292,1460730593,1460751292,False,False,True,canceled
1965,2052582454,"Christina Romeo Ceramic Shop ""Ceni""",1,Ceramics,1.0,art/ceramics,2500.00,8,361.00,False,US,1451584440,1395245090,1448474311,False,False,True,failed
2026,106687835,Phase 2 - NHerr Art - Kiln for Pottery Studio,1,Ceramics,1.0,art/ceramics,3500.00,34,3521.00,False,US,1526227449,1516162246,1523635449,False,True,True,successful
2159,1647500845,Handmade Ceramics!,1,Ceramics,1.0,art/ceramics,575.00,24,776.00,False,US,1327610491,1326395838,1326400891,False,True,True,successful
2285,2093140054,Craft Camp,1,Ceramics,1.0,art/ceramics,5000.00,0,0.00,False,GB,1496327791,1493717920,1493735791,False,False,True,failed
2425,2127172168,Rancho Corvid Community Wood Kiln Project,1,Ceramics,1.0,art/ceramics,16000.00,26,3510.00,False,US,1476817749,1473292098,1474225749,False,False,True,failed
9685,285571039,Handmade lodge lamp,1,Ceramics,1.0,art/ceramics,4500.00,1,1.42,False,RU,1540963987,1528279444,1535779987,False,False,True,live
9761,1271355750,Custom Pottery,1,Ceramics,1.0,art/ceramics,900.00,3,175.00,False,US,1407972329,1405023717,1405380329,False,False,True,failed
16605,302760075,Ki's Kiln,1,Ceramics,1.0,art/ceramics,3700.00,43,4511.00,False,US,1420226147,1417385417,1417634147,False,True,True,successful
18813,1846681496,Bottega Krua: italian handmade ceramics,1,Ceramics,1.0,art/ceramics,4153.00,4,270.00,False,IT,1507549977,1504863028,1504957977,False,False,True,failed
19516,1726865496,Bring clay to The Painted Plate,1,Ceramics,1.0,art/ceramics,4600.00,59,4837.00,False,US,1475301600,1473273070,1473539531,False,True,True,successful
19555,88092201,The Ultimate Salad Spoon,1,Ceramics,1.0,art/ceramics,9000.00,1,1.00,False,US,1461793440,1458258451,1459783471,False,False,True,failed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183304,650280846,AaaahZ Youth Theatre - Footloose the Musical,15,Theater,NaN,theater,3500.00,37,3662.00,False,US,1349472544,1344898323,1346880544,False,True,True,successful
183318,620291573,THE VIVIAN GIRLS: A play with music.,15,Theater,NaN,theater,4500.00,88,5270.11,False,US,1333249200,1329584929,1330100159,True,True,True,successful
183329,1131064386,Little Shop of Horrors is taking over Just Off...,15,Theater,NaN,theater,550.00,13,616.00,False,US,1345754245,1339096033,1343939845,False,True,True,successful
183330,2125423433,'A Chorus Line' by Hamilton Academy of Music,15,Theater,NaN,theater,7000.00,91,9287.00,False,US,1320476340,1316494667,1316620408,False,True,True,successful
183339,1572991736,AwesomeTown in Prague!,15,Theater,NaN,theater,5555.55,50,6146.00,False,US,1308412800,1303831849,1303840257,False,True,True,successful
183341,290868303,THE ROCK & THE RIPE,15,Theater,NaN,theater,7000.00,154,7943.00,False,US,1336517348,1330994970,1331336948,False,True,True,successful
183346,1735737409,Sleeping Beauty,15,Theater,NaN,theater,5000.00,55,5445.00,False,US,1300690800,1297029737,1297050338,False,True,True,successful
183358,544579463,Veronika Decides to Die: a theatrical adaptati...,15,Theater,NaN,theater,500.00,15,550.00,False,US,1289168642,1286567667,1286573042,False,True,True,successful
183412,475145187,FALSETTOS at NYU,15,Theater,NaN,theater,1200.00,15,1200.00,False,US,1302645600,1300303628,1300313110,False,True,True,successful
183415,484383783,"A Midsummer Night's Dream in Snowmass, Colorado!",15,Theater,NaN,theater,1000.00,34,1905.00,False,US,1311185214,1309449483,1309457214,False,True,True,successful
183417,1138278535,Women's Soccer Play (Phase 1: On-Site Research),15,Theater,NaN,theater,3000.00,60,3101.00,False,CM,1327091261,1323374921,1324499261,False,True,True,successful
183418,539662960,GLORY DAYS in Concert,15,Theater,NaN,theater,2500.00,34,2510.00,False,US,1292465220,1288753096,1289001544,False,True,True,successful
183419,974568641,Truckin' for Duke City Rep,15,Theater,NaN,theater,5000.00,79,5365.00,False,US,1326061137,1322889906,1323469137,False,True,True,successful
183423,1431799205,EDITH CAN SHOOT THINGS AND HIT THEM,15,Theater,NaN,theater,5000.00,110,5327.00,False,US,1346396400,1340161855,1341937051,False,True,True,successful
184559,334563601,"Enfrascada, A Hoodoo Comedy of Jarring Proport...",15,Theater,NaN,theater,555.00,19,570.00,False,US,1335574309,1332358178,1332982309,False,True,True,successful
184582,194078133,The Useless Secret Weapon of Jacob Thompson,15,Theater,NaN,theater,3500.00,35,3586.00,False,US,1337882318,1333586158,1335290318,False,True,True,successful
184583,1709579043,Gospel According to First Squad,15,Theater,NaN,theater,3333.33,134,3860.00,False,US,1309849140,1283568705,1306739233,False,True,True,successful
184599,705003712,Stephen Sondheim's Assassins,15,Theater,NaN,theater,5000.00,24,6231.66,False,US,1329675977,1314131728,1325787977,False,True,True,successful
184606,331681865,The Magical History Tour: Theater! On a Boat! ...,15,Theater,NaN,theater,20000.00,96,20811.00,False,US,1340228290,1332982966,1337636290,True,True,True,successful
184607,756379644,SEXUAL PERVERSITY IN CHICAGO by David Mamet,15,Theater,NaN,theater,1500.00,29,1550.00,False,US,1349457336,1344988875,1346865336,False,True,True,successful
184611,292128675,The Twentieth-Century Way,15,Theater,NaN,theater,1000.00,19,1160.00,False,US,1335931200,1331328580,1331851430,False,True,True,successful
184614,1257297523,The Fall Harvest: two short plays by A. Miller...,15,Theater,NaN,theater,3000.00,42,3026.00,False,US,1350073845,1346339569,1347913845,True,True,True,successful
184615,1746021999,Merely Players is back: The Shape of Things,15,Theater,NaN,theater,1200.00,47,2635.00,False,US,1310356740,1308170152,1308315817,False,True,True,successful
184616,872890814,"""Now That She's Gone"" to Edinburgh!",15,Theater,NaN,theater,25000.00,168,25001.00,False,GB,1303869306,1298596777,1298602506,False,True,True,successful
184619,1689272208,The tragedy of AMLETH princess of Denmark,15,Theater,NaN,theater,5000.00,69,5115.00,False,US,1350090787,1344394967,1344906787,False,True,True,successful
184620,1662189213,"""Hot Summer Fun"" with Your Terrific Neighbors",15,Theater,NaN,theater,500.00,22,515.00,False,US,1247673600,1244225724,1244227730,False,True,True,successful
184621,1409667422,The 3rd Annual Working Theater Directors Salon,15,Theater,NaN,theater,2500.00,81,3050.00,False,US,1334462340,1332275474,1332550006,False,True,True,successful
184622,660575286,"Coyote StageWorks $50,000 DRIVE - Be a ""Tuna H...",15,Theater,NaN,theater,10000.00,103,11640.00,False,US,1291104000,1288637994,1288683558,False,True,True,successful
184637,1648884485,"""Hamlet Shut Up"" ~ Classic Tragedy, Silent Com...",15,Theater,NaN,theater,3300.00,108,4150.97,False,US,1281369600,1277228891,1278702039,True,True,True,successful
184658,1793604320,Retrofit Caffeinated Cabaret's New Venue!,15,Theater,NaN,theater,1500.00,30,1520.00,False,US,1299555000,1297908878,1298335568,False,True,True,successful

In [149]:
len(df.sub_category_id.unique())

19

In [150]:
len(df.sub_category.unique())

159

In [153]:
len(df.category_id.unique())

16

In [154]:
len(df.category.unique())

169

In [155]:
# The number of category IDs does not match the category titles (same for sub-).

In [165]:
df.sort_values(by='sub_category_id').sub_category_id.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19], dtype=int64)

In [170]:
df[df.sub_category_id == 1].sub_category.unique()

array(['Audio', 'Animals', 'Candles', 'Bacon', 'Accessories', 'Art',
       'Ceramics', 'Performances', 'Gaming Hardware', '3D Printing',
       'Action', 'Comedy', 'Anthologies', 'Academic', 'Blues',
       'Architecture'], dtype=object)

In [171]:
df[df.sub_category_id == 2].sub_category.unique()

array(['Animation', 'Experimental', 'Comics', 'Comic Books',
       'Anthologies', 'Apps', 'Conceptual Art', 'Residencies', 'Crochet',
       'Photo', 'Fine Art', 'Apparel', 'Civic Design',
       'Community Gardens', 'Chiptune', 'Live Games'], dtype=object)

In [172]:
df[df.sub_category_id == 3].sub_category.unique()

array(['Spaces', 'Crafts', 'Camera Equipment', 'Comedy', 'Nature', 'DIY',
       'Art Books', 'Digital Art', 'Mobile Games', 'Childrenswear',
       'Classical Music', 'Festivals', 'Events', 'Cookbooks', 'Print',
       'Graphic Design'], dtype=object)

In [173]:
df[df.sub_category_id == 4].sub_category.unique()

array(['Embroidery', 'Playing Cards', 'Illustration', 'Calendars',
       'Graphic Novels', 'DIY Electronics', 'Couture', 'Video', 'Dance',
       'People', 'Immersive', 'Documentary', 'Drinks',
       'Interactive Design', 'Workshops', 'Comedy'], dtype=object)

In [174]:
df[df.sub_category_id == 5].sub_category.unique()

array(['Footwear', 'Webcomics', 'Photobooks', 'Musical',
       "Children's Books", 'Country & Folk', 'Puzzles',
       'Fabrication Tools', 'Glass', 'Product Design', 'Design',
       'Installations', 'Drama', 'Events', 'Web'], dtype=object)

In [ ]:
# there does not seem to be a strong correlation between sub_category_id and sub_category. Let's drop the sub_category_id 
# and (maybe) keep sub_category

In [198]:
df.sort_values(by='category_id').category_id.unique()

array([ 1.,  3.,  6.,  7.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 26., nan])

In [176]:
df[df.category_id == 1].category.unique()

array(['art/painting', 'art/textiles', 'art/illustration',
       'art/mixed media', 'art/ceramics', 'art/sculpture',
       'art/digital art', 'art/conceptual art', 'art/public art',
       'art/performance art', 'art/installations', 'art/video art'],
      dtype=object)

In [178]:
df[df.category_id == 3].category.unique()

array(['comics/webcomics', 'comics/comic books', 'comics/graphic novels',
       'comics/events', 'comics/anthologies'], dtype=object)

In [179]:
df[df.category_id == 6].category.unique()

array(['dance/spaces', 'dance/performances', 'dance/residencies',
       'dance/workshops'], dtype=object)

In [180]:
df[df.category_id == 7].category.unique()

array(['design/product design', 'design/civic design',
       'design/interactive design', 'design/typography',
       'design/graphic design', 'design/architecture'], dtype=object)

In [181]:
df[df.category_id == 9].category.unique()

array(['fashion/footwear', 'fashion/accessories', 'fashion/ready-to-wear',
       'fashion/couture', 'fashion/childrenswear', 'fashion/pet fashion',
       'fashion/apparel', 'fashion/jewelry'], dtype=object)

In [182]:
df[df.category_id == 10].category.unique()

array(['food/bacon', 'food/vegan', 'food/restaurants', 'food/food trucks',
       'food/cookbooks', 'food/small batch', 'food/farms', 'food/events',
       'food/drinks', 'food/spaces', 'food/community gardens',
       "food/farmer's markets"], dtype=object)

In [183]:
df[df.category_id == 11].category.unique()

array(['film & video/animation', 'film & video/family',
       'film & video/comedy', 'film & video/horror',
       'film & video/fantasy', 'film & video/music videos',
       'film & video/narrative film', 'film & video/movie theaters',
       'film & video/action', 'film & video/romance',
       'film & video/webseries', 'film & video/shorts',
       'film & video/festivals', 'film & video/drama',
       'film & video/documentary', 'film & video/thrillers',
       'film & video/television', 'film & video/experimental',
       'film & video/science fiction'], dtype=object)

In [184]:
df[df.category_id == 12].category.unique()

array(['games/video games', 'games/playing cards', 'games/tabletop games',
       'games/mobile games', 'games/gaming hardware', 'games/puzzles',
       'games/live games'], dtype=object)

In [185]:
df[df.category_id == 13].category.unique()

array(['journalism/audio', 'journalism/video', 'journalism/photo',
       'journalism/print', 'journalism/web'], dtype=object)

In [186]:
df[df.category_id == 14].category.unique()

array(['music/jazz', 'music/electronic music', 'music/faith', 'music/pop',
       'music/metal', 'music/r&b', 'music/kids', 'music/hip-hop',
       'music/country & folk', 'music/rock', 'music/classical music',
       'music/indie rock', 'music/world music', 'music/latin',
       'music/punk', 'music/blues', 'music/comedy', 'music/chiptune'],
      dtype=object)

In [187]:
df[df.category_id == 15].category.unique()

array(['photography/photobooks', 'photography/animals',
       'photography/places', 'photography/nature', 'photography/fine art',
       'photography/people'], dtype=object)

In [188]:
df[df.category_id == 16].category.unique()

array(['technology/web', 'technology/hardware',
       'technology/camera equipment', 'technology/software',
       'technology/wearables', 'technology/makerspaces',
       'technology/sound', 'technology/robots', 'technology/apps',
       'technology/diy electronics', 'technology/gadgets',
       'technology/3d printing', 'technology/fabrication tools',
       'technology/space exploration', 'technology/flight'], dtype=object)

In [189]:
df[df.category_id == 17].category.unique()

array(['theater/experimental', 'theater/spaces', 'theater/musical',
       'theater/plays', 'theater/festivals', 'theater/comedy',
       'theater/immersive'], dtype=object)

In [191]:
df[df.category_id == 18].category.unique()

array(['publishing/letterpress', 'publishing/periodicals',
       'publishing/radio & podcasts', "publishing/children's books",
       'publishing/nonfiction', 'publishing/anthologies',
       'publishing/fiction', 'publishing/poetry', 'publishing/calendars',
       'publishing/art books', 'publishing/literary journals',
       'publishing/translations', 'publishing/literary spaces',
       'publishing/zines', 'publishing/academic',
       'publishing/young adult', 'publishing/comedy'], dtype=object)

In [193]:
df[df.category_id == 26].category.unique()

array(['crafts/woodworking', 'crafts/quilts', 'crafts/embroidery',
       'crafts/knitting', 'crafts/candles', 'crafts/diy',
       'crafts/stationery', 'crafts/crochet', 'crafts/pottery',
       'crafts/glass', 'crafts/weaving', 'crafts/printing',
       'crafts/taxidermy'], dtype=object)

In [229]:
df[np.isnan(df.category_id)].category.unique()

array(['theater', 'photography', 'crafts', 'comics', 'technology', 'art',
       'publishing', 'music', 'dance', 'fashion', 'design', 'games',
       'film & video', 'journalism', 'food'], dtype=object)

In [232]:
df.sort_values('sub_category').sub_category.unique()

array(['3D Printing', 'Academic', 'Accessories', 'Action', 'Animals',
       'Animation', 'Anthologies', 'Apparel', 'Apps', 'Architecture',
       'Art', 'Art Books', 'Audio', 'Bacon', 'Blues', 'Calendars',
       'Camera Equipment', 'Candles', 'Ceramics', "Children's Books",
       'Childrenswear', 'Chiptune', 'Civic Design', 'Classical Music',
       'Comedy', 'Comic Books', 'Comics', 'Community Gardens',
       'Conceptual Art', 'Cookbooks', 'Country & Folk', 'Couture',
       'Crafts', 'Crochet', 'DIY', 'DIY Electronics', 'Dance', 'Design',
       'Digital Art', 'Documentary', 'Drama', 'Drinks',
       'Electronic Music', 'Embroidery', 'Events', 'Experimental',
       'Fabrication Tools', 'Faith', 'Family', 'Fantasy',
       "Farmer's Markets", 'Farms', 'Fashion', 'Festivals', 'Fiction',
       'Film & Video', 'Fine Art', 'Flight', 'Food', 'Food Trucks',
       'Footwear', 'Gadgets', 'Games', 'Gaming Hardware', 'Glass',
       'Graphic Design', 'Graphic Novels', 'Hardware', 'Hip-Hop',
       'Horror', 'Illustration', 'Immersive', 'Indie Rock',
       'Installations', 'Interactive Design', 'Jazz', 'Jewelry',
       'Journalism', 'Kids', 'Knitting', 'Latin', 'Letterpress',
       'Literary Journals', 'Literary Spaces', 'Live Games',
       'Makerspaces', 'Metal', 'Mixed Media', 'Mobile Games',
       'Movie Theaters', 'Music', 'Music Videos', 'Musical',
       'Narrative Film', 'Nature', 'Nonfiction', 'Painting', 'People',
       'Performance Art', 'Performances', 'Periodicals', 'Pet Fashion',
       'Photo', 'Photobooks', 'Photography', 'Places', 'Playing Cards',
       'Plays', 'Poetry', 'Pop', 'Pottery', 'Print', 'Printing',
       'Product Design', 'Public Art', 'Publishing', 'Punk', 'Puzzles',
       'Quilts', 'R&B', 'Radio & Podcasts', 'Ready-to-wear',
       'Residencies', 'Restaurants', 'Robots', 'Rock', 'Romance',
       'Science Fiction', 'Sculpture', 'Shorts', 'Small Batch',
       'Software', 'Sound', 'Space Exploration', 'Spaces', 'Stationery',
       'Tabletop Games', 'Taxidermy', 'Technology', 'Television',
       'Textiles', 'Theater', 'Thrillers', 'Translations', 'Typography',
       'Vegan', 'Video', 'Video Art', 'Video Games', 'Wearables',
       'Weaving', 'Web', 'Webcomics', 'Webseries', 'Woodworking',
       'Workshops', 'World Music', 'Young Adult', 'Zines'], dtype=object)

In [233]:
df.sort_values('category').category.unique()

array(['art', 'art/ceramics', 'art/conceptual art', 'art/digital art',
       'art/illustration', 'art/installations', 'art/mixed media',
       'art/painting', 'art/performance art', 'art/public art',
       'art/sculpture', 'art/textiles', 'art/video art', 'comics',
       'comics/anthologies', 'comics/comic books', 'comics/events',
       'comics/graphic novels', 'comics/webcomics', 'crafts',
       'crafts/candles', 'crafts/crochet', 'crafts/diy',
       'crafts/embroidery', 'crafts/glass', 'crafts/knitting',
       'crafts/pottery', 'crafts/printing', 'crafts/quilts',
       'crafts/stationery', 'crafts/taxidermy', 'crafts/weaving',
       'crafts/woodworking', 'dance', 'dance/performances',
       'dance/residencies', 'dance/spaces', 'dance/workshops', 'design',
       'design/architecture', 'design/civic design',
       'design/graphic design', 'design/interactive design',
       'design/product design', 'design/typography', 'fashion',
       'fashion/accessories', 'fashion/apparel', 'fashion/childrenswear',
       'fashion/couture', 'fashion/footwear', 'fashion/jewelry',
       'fashion/pet fashion', 'fashion/ready-to-wear', 'film & video',
       'film & video/action', 'film & video/animation',
       'film & video/comedy', 'film & video/documentary',
       'film & video/drama', 'film & video/experimental',
       'film & video/family', 'film & video/fantasy',
       'film & video/festivals', 'film & video/horror',
       'film & video/movie theaters', 'film & video/music videos',
       'film & video/narrative film', 'film & video/romance',
       'film & video/science fiction', 'film & video/shorts',
       'film & video/television', 'film & video/thrillers',
       'film & video/webseries', 'food', 'food/bacon',
       'food/community gardens', 'food/cookbooks', 'food/drinks',
       'food/events', "food/farmer's markets", 'food/farms',
       'food/food trucks', 'food/restaurants', 'food/small batch',
       'food/spaces', 'food/vegan', 'games', 'games/gaming hardware',
       'games/live games', 'games/mobile games', 'games/playing cards',
       'games/puzzles', 'games/tabletop games', 'games/video games',
       'journalism', 'journalism/audio', 'journalism/photo',
       'journalism/print', 'journalism/video', 'journalism/web', 'music',
       'music/blues', 'music/chiptune', 'music/classical music',
       'music/comedy', 'music/country & folk', 'music/electronic music',
       'music/faith', 'music/hip-hop', 'music/indie rock', 'music/jazz',
       'music/kids', 'music/latin', 'music/metal', 'music/pop',
       'music/punk', 'music/r&b', 'music/rock', 'music/world music',
       'photography', 'photography/animals', 'photography/fine art',
       'photography/nature', 'photography/people',
       'photography/photobooks', 'photography/places', 'publishing',
       'publishing/academic', 'publishing/anthologies',
       'publishing/art books', 'publishing/calendars',
       "publishing/children's books", 'publishing/comedy',
       'publishing/fiction', 'publishing/letterpress',
       'publishing/literary journals', 'publishing/literary spaces',
       'publishing/nonfiction', 'publishing/periodicals',
       'publishing/poetry', 'publishing/radio & podcasts',
       'publishing/translations', 'publishing/young adult',
       'publishing/zines', 'technology', 'technology/3d printing',
       'technology/apps', 'technology/camera equipment',
       'technology/diy electronics', 'technology/fabrication tools',
       'technology/flight', 'technology/gadgets', 'technology/hardware',
       'technology/makerspaces', 'technology/robots',
       'technology/software', 'technology/sound',
       'technology/space exploration', 'technology/wearables',
       'technology/web', 'theater', 'theater/comedy',
       'theater/experimental', 'theater/festivals', 'theater/immersive',
       'theater/musical', 'theater/plays', 'theater/spaces'], dtype=object)

# CATEGORY NOTES

So, what do we keep? It doesn't make much sense to keep sub-categories without the parent category. And for now, dealing with so many categories to begin with it might become overwhelming trying to manage sub-categories too. Let's start with just categories and see if we can make some good predictions (and remember that we can always beef up the algorithm later by adding in the sub-category variables).

As for the category variables, do we want to extract the parent category (eg 'technology') or do we want to keep the sub-categories tacked on (eg 'technology/3d printing' and 'technology/apps')? For now, as mentioned above, let's drop the sub-categories (eg 'technology/3d printing' and 'technology/apps' are both just considered 'technology'). 

We now have two choices: keep the category as categorical or use the IDs. For context, let's keep the categories as categorical and use dummy variables later as needed.

In [234]:
df.columns

Index(['id', 'name', 'sub_category_id', 'sub_category', 'category_id',
       'category', 'goal', 'backers_count', 'pledged', 'disable_communication',
       'country', 'deadline', 'created_at', 'launched_at', 'staff_pick',
       'spotlight', 'creator_registered', 'launch_state'],
      dtype='object')

In [237]:
df.drop(columns=['sub_category_id','sub_category','category_id'], inplace=True)

C:\Users\steve\Anaconda3\lib\site-packages\pandas\core\frame.py:3694: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [240]:
len(df.columns)

15

In [252]:
# Now let's extract the primary category from the category column
df.category[0]

'technology/web'

In [270]:
df.category[0].split('/')[0]

'technology'

In [275]:
df.category[24:28]

24         technology/web
25                theater
26            photography
27    technology/hardware
Name: category, dtype: object

In [276]:
[i.split('/')[0] for i in df.category][24:28]

['technology', 'theater', 'photography', 'technology']

In [277]:
df.category = [i.split('/')[0] for i in df.category]

C:\Users\steve\Anaconda3\lib\site-packages\pandas\core\generic.py:4401: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [279]:
df.sort_values(by='category').category.unique()

array(['art', 'comics', 'crafts', 'dance', 'design', 'fashion',
       'film & video', 'food', 'games', 'journalism', 'music',
       'photography', 'publishing', 'technology', 'theater'], dtype=object)

In [282]:
len(df.category.unique())

15

In [285]:
# We are left with 15 categories.
df.columns

Index(['id', 'name', 'category', 'goal', 'backers_count', 'pledged',
       'disable_communication', 'country', 'deadline', 'created_at',
       'launched_at', 'staff_pick', 'spotlight', 'creator_registered',
       'launch_state'],
      dtype='object')

In [284]:
df.to_csv('analysis.csv', sep=',')

In [288]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187074 entries, 0 to 187073
Data columns (total 15 columns):
id                       187074 non-null int64
name                     187074 non-null object
category                 187074 non-null object
goal                     187074 non-null float64
backers_count            187074 non-null int64
pledged                  187074 non-null float64
disable_communication    187074 non-null bool
country                  186198 non-null object
deadline                 187074 non-null int64
created_at               187074 non-null int64
launched_at              187074 non-null int64
staff_pick               187074 non-null bool
spotlight                187074 non-null bool
creator_registered       187074 non-null bool
launch_state             187074 non-null object
dtypes: bool(4), float64(2), int64(5), object(4)
memory usage: 16.4+ MB

In [300]:
df.deadline[0]

1417150740

In [351]:
# Convert relevant values to datetime 
# The default format of these values is in unix time format
df['deadline'] = df['deadline'].apply(datetime.utcfromtimestamp)
df['created_at'] = df['created_at'].apply(datetime.utcfromtimestamp)
df['launched_at'] = df['launched_at'].apply(datetime.utcfromtimestamp)

C:\Users\steve\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [357]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187074 entries, 0 to 187073
Data columns (total 15 columns):
id                       187074 non-null int64
name                     187074 non-null object
category                 187074 non-null object
goal                     187074 non-null float64
backers_count            187074 non-null int64
pledged                  187074 non-null float64
disable_communication    187074 non-null bool
country                  186198 non-null object
deadline                 187074 non-null datetime64[ns]
created_at               187074 non-null datetime64[ns]
launched_at              187074 non-null datetime64[ns]
staff_pick               187074 non-null bool
spotlight                187074 non-null bool
creator_registered       187074 non-null bool
launch_state             187074 non-null object
dtypes: bool(4), datetime64[ns](3), float64(2), int64(2), object(4)
memory usage: 16.4+ MB

# Stopped here

In [ ]:
# ---- Drop columns ----
to_drop = [
    "Edition Statement",
    "Corporate Author",
    "Corporate Contributors",
    "Former owner",
    "Engraver",
    "Contributors",
    "Issuance type",
    "Shelfmarks"]

df.drop(columns=to_drop, inplace=True)

In [ ]:
df.head()

In [ ]:
# ---- Change index ----
df["Identifier"].is_unique

In [ ]:
df.set_index("Identifier", inplace=True)
df.head(10)

In [ ]:
# ---- Clean specific columns ----
df.get_dtype_counts()

In [ ]:
# ---- Dates ----
  # Extract first 4-digit numbers to be the year
  # This removes any punctuations, converts data ranges to start dates, and changes any non-conforming cells to NaN
extr = df["Date of Publication"].str.extract(r'^(\d{4})', expand=False)
df["Date of Publication"] = pd.to_numeric(extr)
df["Date of Publication"]

In [ ]:
print(f"{round(df['Date of Publication'].isnull().sum() / len(df) * 100,1)}% of the data is null.")

In [ ]:
# ---- Locations ----
  # Use np.where(condition, then, else)
df["Place of Publication"].head(10)

In [ ]:
pub.nunique()

In [ ]:
pub.unique()

In [ ]:
pub = df["Place of Publication"]
london = pub.str.contains("London")
london[:10]

In [ ]:
oxford = pub.str.contains("Oxford")
oxford[:10]

In [ ]:
# Fix "London", "Oxford", and entries with "-"
df["Place of Publication"] = np.where(london, "London",
    np.where(oxford, "Oxford",
    pub.str.replace("-", " ")))
df["Place of Publication"].head(10)

In [ ]:
df["Place of Publication"].nunique()

In [ ]:
# ... Repeat for all data
df["Place of Publication"].unique()

In [ ]:
coventry = pub.str.contains("Coventry")
merida_de_yucatan = pub.str.contains("Merida de Yucatan")
moscow = pub.str.contains("Moscow|Москва|Moskwa")

df["Place of Publication"] = np.where(coventry, "Coventry",
    np.where(merida_de_yucatan, "Merida de Yucatan",
    np.where(moscow, "Moscow",df["Place of Publication"])))

print(f"Number of unique entries: {df['Place of Publication'].nunique()}")
print(f"Unique entries: {df['Place of Publication'].unique()}")

In [ ]:
paris = pub.str.contains("Paris")
lyon = pub.str.contains("Lyon")
moscow = pub.str.contains("Москвѣ")

df["Place of Publication"] = np.where(paris, "Paris",
    np.where(lyon, "Lyon",
    np.where(moscow, "Moscow", df["Place of Publication"])))

print(f"Number of unique entries: {df['Place of Publication'].nunique()}")
print(f"Unique entries: {df['Place of Publication'].unique()}")

In [ ]:
nottingham = pub.str.contains("Nottingham")
viena = pub.str.contains("Viena")

df["Place of Publication"] = np.where(nottingham, "Nottingham",
    np.where(viena, "Viena", df["Place of Publication"]))

print(f"Number of unique entries: {df['Place of Publication'].nunique()}")
print(f"Unique entries: {df['Place of Publication'].unique()}")

In [ ]:
df.groupby(["Place of Publication"]).describe()

In [ ]:
# ---- Convert locations column to categorical ----
"""
place = pd.get_dummies(df["Place of Publication"],drop_first=True)
df.drop(["Place of Publication"],axis=1,inplace=True)
df = pd.concat([df,place],axis=1)
df.head(10)
"""

In [ ]:
# ---- Clean entire dataset using applymap ----
!more Datasets\\university_towns.txt

In [ ]:
university_towns = []
with open("Datasets/university_towns.txt") as file:
    for line in file:
        if "[edit]" in line:
            # Remember this state until the next is found
            state = line
        else:
            # Otherwise we have a city - keep the state
            university_towns.append((state, line))
        
university_towns

In [ ]:
towns_df = pd.DataFrame(university_towns, columns=["State", "RegionName"])
towns_df

In [ ]:
# Function: Grab state and city data
def get_citystate(item):
    if " (" in item:
        return item[:item.find(" (")]
    elif "[" in item:
        return item[:item.find("[")]
    else:
        return item

In [ ]:
# applymap the function
towns_df = towns_df.applymap(get_citystate)
towns_df

In [ ]:
# ---- Organize column labels ----
olympics_df = pd.read_csv("Datasets/olympics.csv")
olympics_df

In [ ]:
# Skip the top row and set the header
olympics_df = pd.read_csv("Datasets/olympics.csv", header=1)
olympics_df

In [ ]:
# Rename the columns
olympics_df.columns

In [ ]:
new_names = {'Unnamed: 0': 'Country',
            '? Summer': 'Summer Olympics',
            '01 !': 'Gold',
            '02 !': 'Silver',
            '03 !': 'Bronze',
            '? Winter': 'Winter Olympics',
            '01 !.1': 'Gold.1',
            '02 !.1': 'Silver.1',
            '03 !.1': 'Bronze.1',
            '? Games': '# Games',
            '01 !.2': 'Gold.2',
            '02 !.2': 'Silver.2',
            '03 !.2': 'Bronze.2'}

In [ ]:
olympics_df.rename(columns=new_names, inplace=True)
olympics_df